percona/everest

.github/workflows/dev-build.yaml

As it turned out, there is no need at all for `mkdir` command in the FE build which I added to be sure that the directory exists. 
Without the `-p` option it fails in case the directory exists, so it's deleted

EVEREST-665 dev build fix

---

deploy/quickstart-k8s.yaml
embed.go
pkg/install/install.go
pkg/kubernetes/kubernetes.go
pkg/version/version.go

EVEREST-726 
Now the manifest file is in the same repo as the cli, so there is no need for the logic that differentiate the branches to pick up the manifest from.

EVEREST-726 use internal manifest

---

.github/workflows/dev-be-ci.yaml
.github/workflows/dev-fe-ci.yaml
README.md

**Problem** 
Need to set the different sets of checks for FE and API+CLI as required (to block PR merge if smth is failed). 
GitHub doesn't allow to set the required checks conditionally.
**Solution**
Use merge-gatekeeper github action. It fails if any of the configured checks are failed, so it's added to both API+CLI and UI CI and now we can make only the gatekeeper check as required. [Here](https://github.com/percona/everest/actions/runs/8143600237?pr=30) is how it looks like
**Action needed after merge:**
set "Merge Gatekeeper" check as required

EVEREST-107 Add gatekeeper

---

deploy/quickstart-k8s.yaml
go.mod
go.sum

We don't really need pod anti-affinity rules. We only run a single replica so the high-availability is clearly not a concern right now. Also users that are testing out everest on single node clusters wouldn't be able to upgrade everest due to this constraint.

EVEREST-107 remove pod anti-affinity rules

---

ui/apps/everest/src/pages/settings/storage-locations/createEditModal/create-edit-modal.tsx

[EVEREST-926](https://perconadev.atlassian.net/browse/EVEREST-926)
[EVEREST-926]: https://perconadev.atlassian.net/browse/EVEREST-926?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UI] EVEREST-926 Fix 'Add storage' dialog width

---

.github/workflows/dev-fe-ci.yaml
CONTRIBUTING.md

EVEREST-107 fix FE CI
Previously the `stefanzweifel/git-auto-commit-action@v5` was fine with unexisting (as it turned out) parameter, but at some point it's not anymore. So deleted the parameter. The CI checks are passing.

EVEREST-107 put requests metadata validation

---

pkg/kubernetes/kubernetes.go
pkg/uninstall/uninstall.go

If the installation fails, the uninstallation process fails too as there are certain resources that it expects to be present.
Improve error handling, so that when certain resources are missing (due to failed installation), uninstallation assumes that it is gone, and proceeds further.

EVEREST-947 | Improve error handling during uninstallation

---

ui/apps/everest/src/components/actionable-alert/ActionableAlert.tsx

[EVEREST-948](https://perconadev.atlassian.net/browse/EVEREST-948)
[EVEREST-948]: https://perconadev.atlassian.net/browse/EVEREST-948?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UI] EVEREST-948 Actionable Alert button is not visible in dark theme

---

ui/apps/everest/src/modals/restore-db-modal/restore-db-modal.tsx
ui/apps/everest/src/pages/databases/lastBackup/LastBackup.tsx

[EVEREST-940](https://perconadev.atlassian.net/browse/EVEREST-940)
Also added arrow for warning icon
[EVEREST-940]: https://perconadev.atlassian.net/browse/EVEREST-940?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UI] EVEREST-940 Open Documentation link on PITR in new tab

---

cmd/config/config.go

EVEREST-964 
As discussed during the demo, increases the default rate limit to 100 requests per second considering how many requests does the FE do and the fact that with bigger amount of databases the end users may run into rate limiting problems soon.

EVEREST-964 increase default rate limit

---

pkg/upgrade/upgrade.go
pkg/upgrade/upgrade_test.go

EVEREST-972
Upgrade to the latest patch version, if next minor version is not available.
Skip patch versions if next minor version is available.

EVEREST-972: improve version detection logic

---

pkg/kubernetes/kubernetes.go

Currently, `install` approves the `InstallPlanRef` from the the Subscription, which may change over time (because of OLM). This means that running `install` twice can result in the installation of an undesired operator version (CSV).
- We use the `installedCSV` from the Subscription status
- During the first installation, `installedCSV` is empty, so we take `startingCSV`
- `startingCSV` may be unspecified since it is optional, then we take the `InstallPlanRef`

EVEREST-980 | (Bug fix) Ensure install approves the correct InstallPlan

---

api/validation.go
api/validation_test.go
go.mod

This PR adds the ability to edit/update the database server (engine) version. This is required as a part of the components upgrade feature. However, the following restrictions will apply:
- Prevent downgrades
- Prevent major version upgrades (since they're handled differently for different operators)
TODO:
- Allow updating this version from the UI

EVEREST-976 | allow updating DBEngine version

---

pkg/upgrade/upgrade.go

Fix `nil` value in catalog version log

EVEREST-107: catalog version logging fix

---

.github/workflows/release.yml

EVEREST-107
During the RC for `0.10.0-rc3` there are discovered a couple of problems:
1. Inverted condition that checks mentions of the version in the catalog
2. For the operator the `make release` command always generates changes bc the date changes. So moved the `make release` so that on the second run with the same tag it wouldn't generate any changes. 
Both changes are related to [the temporary process](https://github.com/percona/everest/pull/226#discussion_r1574756469) for the RC/Release we agreed to have until it's automated

EVEREST-107 update release workflow

---

pkg/common/constants.go
pkg/install/install.go
pkg/kubernetes/client/client.go
pkg/kubernetes/client/deployment.go
pkg/kubernetes/client/kubeclient_interface.go
pkg/kubernetes/client/mock_kube_client_connector.go
pkg/kubernetes/deployment.go
pkg/kubernetes/kubernetes.go
pkg/kubernetes/kubernetes_interface.go
pkg/kubernetes/mock_kubernetes_connector.go

Running `install` more than twice concurrently can lead to one of them failing at the Everest restart step.
The current logic of the `RestartEverest` method lists all the pods for a Deployment and deletes them one after the other. Running install twice could lead to a NotFound error during delete as the previous run could have deleted the pods already, which means the latest install run is listing stale/deleted pods.
Instead of having to list and re-create pods from code, handle restart by adding the `kubectl.kubernetes.io/restartedAt` annotation, which is how the `kubectl rollout restart` command works.
- For individual Deployments, add the annotation to the `.spec.template.metadata` section
- For OLM-managed Deployments, add the annotation to the parent CSV's `metadata.annotations` …

EVEREST-1003 | install: improve Everest restart logic

---

.github/workflows/release.yml

EVEREST-107
**Problem:**
During the release it turned out that the condition which interrupts the RC/Release for the manual catalog update step didn't work correctly: if there is a RC version `0.10.0-rcN` mentioned in catalog it considered `0.10.0` as to be already present, which is not correct.

EVEREST-107 fix release.yaml

---

api-tests/playwright.config.ts
api-tests/tests/database-cluster-backups.spec.ts
api-tests/tests/database-cluster-restores.spec.ts
api-tests/tests/database-cluster.spec.ts
api-tests/tests/helpers.ts
api-tests/tests/pg-clusters.spec.ts
api-tests/tests/psmdb-clusters.spec.ts
api-tests/tests/pxc-clusters.spec.ts
api/database_cluster.go
api/database_cluster_backup.go
api/database_engine.go
go.mod
go.sum

Earlier, the everest-operator always preserved backup storage by default. Now the behaviour has reversed, meaning that the operator will now delete the storage always by default. In order to preserve the storage, we must set a specific finalizer on the backups.
This change in behaviour has been introduced in order to allow storage clean-up for backups that are deleted due to retention settings.

EVEREST-979 | Reverse the behaviour of backup storage clean-up

---

Makefile
pkg/version/version.go

Currently the CI uses the `quickstart-k8s.yaml` file from the main branch when installing Everest. This makes it difficult to test changes with the file. 
The CI build of the CLI should pick up the manifest from the latest commit of the branch.

CI should use manifests from the PR branch during installation

---

pkg/oidc/configure.go

- Provide prompt if empty config provided
- Throw error is empty config provided to prompt
- Try connecting with OIDC provider before storing in ConfigMap

EVEREST-1097 | Add input validation for oidc configure command

---

api/everest.go

EVEREST-1095
The settings API shouldn't be authorized since it contains the settings that are needed to start the Everest application. No sensitive data should be stored in the settings since it is stored in a ConfigMap as a plain text and exposed via an API method that doesn't require authorization.

EVEREST-1095 Unprotect settings API

---

.github/workflows/release.yml

Since we moved 0.0.0 to the top of the list in the veneer file, the latest version in the fast channel is the last one in the list now, but not the second last as it was before

EVEREST-107 fix detection of the latest version

---

pkg/accounts/types.go
pkg/install/install.go
pkg/kubernetes/client/accounts/accounts.go

We should skip the post-install message if the admin password is already hashed after installing Everest once already.

EVEREST-1126 | Skip post-install message if admin password is hashed

---

commands/accounts.go
commands/install.go
commands/root.go
commands/settings.go
commands/settings/oidc.go
commands/settings/oidc/configure.go
commands/uninstall.go
commands/upgrade.go
commands/version.go

Previously we had:
```shell
$ everestctl oidc configure ...
```
Now we will have a `settings` command that manages everything related to settings, including oidc:
```shell
$ everestctl settings oidc configure ...
```
Also adds help messages for every command

EVEREST-1123 | Create `settings` command and move oidc under it

---

pkg/kubernetes/kubernetes.go
pkg/kubernetes/kubernetes_interface.go

`RestartOperator` and `RestartDeployment` methods must retry update operations in order to improve resilience against update conflicts

EVEREST-1128 | Improved resiliency against update conflicts

---

commands/accounts.go
commands/accounts/initial_admin_password.go
pkg/install/install.go

To retrieve the initial admin password, now you can run the following command:
```shell
everestctl accounts initial-admin-password
```
If the password has been reset, it shows the following error:
```shell
2024-06-06T13:20:55.427+0530    ERROR   Cannot retrieve admin password after it has been updated.```

EVEREST-1112 | add command for retrieving initial admin password

---

pkg/common/version.go
pkg/common/version_test.go

Using generics, we're able to enforce a type constraint during compile time, which can prevent possible panics that may occur due to failed/unsupported type casting.

Re-implement CompareVersions helper using generics

---

api/operatorupgrade_preflight.go
api/operatorupgrade_preflight_test.go

"Upgrade DB version to at least X"
This rephrasing allows us to upgrade a DB engine from the upgrade page, by bumping to the most compatible recommended version.

Rephrase preflight message for DB engine upgrade

---

api/monitoring_instance.go
api/validation.go

Since this is a PATCH method users shouldn't need to specify all parameters if they don't want to. If users don't specify the username/password we refrain from updating the secret but still update the MonitoringConfig CR.

EVEREST-865 allow empty username/password in PATCH monitoring-instances

---

api/validation.go
api/validation_test.go

EVEREST-1170
The Everest pg design issues were discovered (the initial bug EVEREST-1161). The problems appear because: 
- the repo names (`repo2`, `repo3`, `repo4`) are not sticky and when Everest edits/deletes schedules the names can shift so all the already taken backups may point out to a not relevant repo 
- repos with the same storage are being considered as the same repo in `pgbackrest`, which messes up the repo names from the pgbackrest side too (idea how to fix: use a unique path for each repo) :
Since it's not feasible to properly implement and test the solution before the GA, it was decided to restrict the following PG functionality until we have a proper fix in the next releases: 
For PG: 
1. Don’t allow to edit the storage in the existing schedules
2. Don’t allow to delete …

EVEREST-1170 Add PG restrictions

---

api/database_cluster_backup.go
api/validation.go

Fix the validation problem:
The key factor here is the `schedules` property. If you send it empty, as long as `enabled = true` , the API will take it.
The API only throws an error if `enabled = true` but the schedule key is absent

API PUT DB cluster validation fix

---

ui/apps/everest/src/hooks/api/db-cluster/useCreateDbCluster.ts
ui/apps/everest/src/hooks/api/db-cluster/useUpdateDbCluster.ts

Issue: previous schedules were sent when all got emptied during cluster edition.
Cause: since schedules in the form were empty, the previous ones were being sent to the API because the override would only happen when some schedule was present.
Solution: schedules key always present. If none on the form, it's set as undefined and removed during the API request

EVEREST-1188 fix: send schedules undefined when none present

---

pkg/kubernetes/kubernetes.go

We introduced this phase check because OLM has a bug where it sometimes creates duplicate InstallPlans for the same CSV and we found a few cases where the duplicate InstallPlan wasn't reconciled correctly and abandoned by OLM. This abandoned InstallPlan was missing the status field meaning it was also missing the necessary plan to install the operator. Approving this InstallPlan would cause the operator to never be installed. By checking the phase we make sure we will be approving an InstallPlan that is actually ready to be approved. See https://github.com/operator-framework/kubectl-operator/issues/13 for more details on a similar issue.

EVEREST-1182 fix install of everest operator

---

dev/Tiltfile

After merging https://github.com/percona/everest/pull/454, we changed the way we look up namespaces managed by Everest - instead of reading from the Deployment, we label namespaces with `app.kubernetes.io/managed-by=everest`, and use it to list namespaces.
However, this label is missing from namespaces managed by Tilt because they're added only during CLI install/upgrade.
This PR ensures that tilt namespaces also have this label.

Ensure correct managed-by label for namespaces managed by tilt

---

dev/Tiltfile

https://github.com/percona/everest/pull/470 doesn't seem to work correctly always. So, update tilt to use `local_resource` to run `kubectl label` command, and add a dependency on the namespaces so tilt always waits for the namespaces to appear first before trying to label it.

Fix namespace labels in tilt setup

---

api/validation.go
api/validation_test.go

While trying to downgrade a major version returns incorrect error message - `Database engine cannot be upgraded to a major version`
With this PR, we first ensure that no downgrades are happening (major or minor) and then proceed to check for major version upgrade.

EVEREST-1233 | Fix order of checks for dbengine version upgrades

---

api/validation.go
api/validation_test.go

EVEREST-1216 
The [investigation](https://docs.google.com/spreadsheets/d/1UHWKdP6Rlgkir03-W5g5Ky2oFTu2aNs5p1awbyfRo4M/edit?gid=0#gid=0) revealed that the schedules deletion causes the messed up PG repos only when Everest allows to use the same storage (url + bucket + region) for several schedules, which is not allowed anymore, so we can get rid of the limitation.

EVEREST-1216 Allow PG storages removal

---

pkg/rbac/rbac.go
pkg/rbac/testdata/policy-7-bad.csv
pkg/rbac/utils/utils.go
pkg/rbac/validate.go
pkg/rbac/validate_test.go

The casbin library we're using lacks proper error handling, and we need to manually add checks for different types of syntax errors. This PR makes the following changes:
- Detect when a policy does not start with `p` or `g`. Earlier this leads to a panic from the casbin library, now we add a check for this so that we have proper error messages.
- Panic everest API when it detects invalid policies. Earlier, Everest was allowed to run with faulty policies. The casbin library simply skipped invalid policy lines and ran with the rest of the config. This can be problematic because now Everest has incomplete RBAC and this may have security implication because the user has no idea about it. With this PR, Everest will now panic when you enter invalid RBAC.
- We should document that it is …

EVEREST-1142 | RBAC stability improvements

---

cli-tests/tests/flow/all-operators.spec.ts
cli-tests/tests/flow/mongodb-operator.spec.ts
cli-tests/tests/flow/pg-operator.spec.ts
cli-tests/tests/flow/pxc-operator.spec.ts
commands/install.go
commands/uninstall.go
commands/upgrade.go
pkg/install/install.go
pkg/uninstall/uninstall.go
pkg/upgrade/upgrade.go

Follow up for https://github.com/percona/everest/pull/505 which broke the pretty printing in the CLI
- Originally https://github.com/percona/everest/pull/505 was intended to fix the Kubernetes connectivity errors not being logged on the CLI before starting the main install/upgrade/uninstall process, but it also broke the pretty printing logic. This PR ensures that pretty printing still works while the Kubernetes errors are also still being logged by our logger.
- Adds CLI tests for pretty output

EVEREST-1235 | [CLI] Fix broken pretty print

---

ui/apps/everest/.e2e/db-cluster/db-wizard/create-db-cluster/create-db-cluster.e2e.ts
ui/apps/everest/.e2e/db-cluster/db-wizard/create-db-cluster/steps/resources-step.ts
ui/apps/everest/.e2e/utils/db-cluster.ts
ui/apps/everest/src/hooks/api/db-cluster/useCreateDbCluster.ts
ui/apps/everest/src/hooks/api/db-cluster/useUpdateDbCluster.ts
ui/apps/everest/src/pages/database-form/database-form-body/steps/resources/resources-step.tsx
ui/apps/everest/src/pages/database-form/database-form-body/steps/resources/resources-step.utils.ts
ui/apps/everest/src/pages/database-form/database-form.utils.ts
ui/apps/everest/src/pages/database-form/database-preview/database-preview.test.tsx
ui/apps/everest/src/pages/database-form/database-preview/sections/resources-section.tsx
ui/apps/everest/src/utils/k8ResourceParser/index.ts
ui/apps/everest/src/utils/k8ResourceParser/k8ResourceParser.test.ts

Revert "feat: use GiB as disk unit"

---

ui/packages/ui-lib/src/buttons/copy-to-clipboard-button/CopyToClipboardButton.tsx
ui/packages/ui-lib/src/buttons/copy-to-clipboard-button/clipboard.messages.ts

[EVEREST-1249](https://perconadev.atlassian.net/browse/EVEREST-1249)
[EVEREST-1249]: https://perconadev.atlassian.net/browse/EVEREST-1249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UI] EVEREST-1249 Fix Tooltip for disabled copy button not showing up

---

.github/workflows/release.yml

**Problem:**
After the 1.1.0 release it turned out that Everest still installs the everest-operator image from `perconalab`:
```
$ kubectl get po -l app.kubernetes.io/name=everest-operator -o yaml -n everest-system | grep image
...
image: docker.io/perconalab/everest-operator:1.1.0
```
**Cause:**
There is this [make bundle](https://github.com/percona/everest-operator/blob/110cb964dedb09bb9e3c0b7411ec00a7e48804c6/Makefile#L246-L250) command which is used during the operator release. This command uses 
the [IMG](https://github.com/percona/everest-operator/blob/110cb964dedb09bb9e3c0b7411ec00a7e48804c6/Makefile#L55) variable, which uses 
the [IMAGE_TAG_BASE](https://github.com/percona/everest-operator/blob/110cb964dedb09bb9e3c0b7411ec00a7e48804c6/Makefile#L33) variable, which uses 
the …

EVEREST-107 update IMAGE_TAG_OWNER

---

dev/Tiltfile

The latest version of `victoria-metrics-operator` 0.34.0 (15 Aug, 2024) doesn't work with the current Tilt configuration.
```
Error in helm: command "helm template victoria-metrics-operator \"/Users/oxanagrishchenko/Library/Application Support/tilt-dev/.helm/vm/latest/victoria-metrics-operator\" --namespace everest-monitoring --include-crds" failed.
error: exit status 1
stdout: ""
stderr: "Error: template: victoria-metrics-operator/templates/deployment.yaml:99:30: executing \"victoria-metrics-operator/templates/deployment.yaml\" at <include \"vm.probe\" (dict \"app\" .Values \"type\" \"readiness\")>: error calling include: template: victoria-metrics-operator/charts/victoria-metrics-common/templates/_probe.tpl:6:4: executing \"vm.probe\" at <tpl (toYaml $probe) .>: error calling tpl: …
```

EVEREST-107 Tiltfile VM operator fix

---

ui/apps/everest/src/pages/db-cluster-details/components/components.constants.ts
ui/apps/everest/src/pages/db-cluster-details/components/components.tsx

After this PR all component with pending status should be in the top of the list

[UI] EVEREST-1382-sorting-components

---

.github/workflows/dev-be-ci.yaml

Minikube images have mysteriously disappeared, and as a result the registry addon cannot be enabled, resulting in CI failures.
Temporary workaround based on this issue thread: https://github.com/kubernetes/minikube/issues/19535

[CI] Fix broken Minikube

---

api/namespace.go
pkg/rbac/rbac.go

**Problem**
After implementing RBAC, `GET /v1/namespaces` works only if you have permssions to read all (*) namepaces. A user should be able to use this API even if they have restricted access to the namespaces.
**Solution**
Always allow the `GET /v1/namespaces` operation, however the result itself is filtered based on the RBAC.

EVEREST-1386 | Filter ListNamespaces based on RBAC permissions

---

pkg/uninstall/uninstall.go
pkg/upgrade/migrate_shared_resources.go

Uninstallation is stuck after upgrading to 1.2.0.
- As a part of the 1.2.0 upgrade, we perform a migration of BackupStorages and MonitoringConfigs
- Prior to 1.2.0, the BackupStorages have a `percona.com/cleanup-secrets` finalizer that was intended to remove Secrets in the DB namespaces
- Uninstallation gets stuck because this finalizer is no longer handled by the operator
Fix:
- Remove the finalizer during the migration, since the Secrets in the DB namespaces are now owned by the newly created local BackupStorage
- Also fix the uninstall code to list BackupStorages/MonitoringConfigs from DB namespaces.

EVEREST-1403 | Fix broken uninstallation after 1.2.0 API migration

---

pkg/upgrade/migrate_shared_resources.go
pkg/upgrade/upgrade.go

In https://github.com/percona/everest/pull/632 we added some code to remove a finalizer from BackupStorages in `everest-system` namespace to unblock uninstallation. However, that code is run before the operator has upgraded. As a result, the operator adds back this finalizer.
To fix this problem, we run the migration after the Everest operator upgrade step, i.e, as a part of the post-upgrade tasks.

EVEREST-1403 | Run 1.2.0 API migration as a part of the post-upgrade step

---

api/validation.go
api/validation_test.go

EVEREST-1404 
Minimal possible number of configservers is set to 1.

EVEREST-1404.2 Update sharding validation

---

.github/workflows/dev-be-ci.yaml
.github/workflows/dev-fe-e2e.yaml
api-tests/tests/database-engines.spec.ts

**Problem:** 
Using a new version of psmdb operator - `1.17.0` which is not yet at `check.percona.com` but only on `check-dev.percona.com`. The CI will fail bc the Everest operator uses the prod VS URL by default
**Solution:**
patch subscription and add the env variable `PERCONA_VERSION_SERVICE_URL` pointing to `https://check-dev.percona.com/versions/v1`

EVEREST-107 patch sub to add VS dev url

---

ui/apps/everest/src/pages/db-cluster-details/backups/backups-list/backups-list-menu-actions.tsx
ui/apps/everest/src/pages/db-cluster-details/db-action-button.tsx

after fix:
create Restore to new DB  is no longer available if permission canCreateRestore is missing (actions menu + row actions button)
(restore to new DB was fixed in EVEREST-1408)

EVEREST-1433-restore-permissions: change create to createRestore permission

---

api/database_engine.go
api/proxy.go
pkg/rbac/rbac.go

Similar to `ListNamespaces` API call, we will allow users to list db-engines, however the response itself shall be filtered based on the RBAC policy.

EVEREST-1428 | Filter ListDatabaseEngines API call based on RBAC

---

deploy/quickstart-k8s.yaml

Add `'*'` action for `namespaces` and `database-cluster-credentials`. Doesn't change anything in terms of functionality, just future-proofing.

[RBAC] Update default admin role

---

.github/minio.conf.yaml

Minio which is used for UI E2E tests is executed as a Pod kind which often fails and the Pod will not be restarted and the tests fail (often seen when executing locally), so it is better to use a Deployment kind which will restart the Pod if it faces some issues.

EVEREST-1461 - Change test MinIO from Pod to Deployment

---

api/database_cluster.go
api/monitoring_instance.go
pkg/rbac/rbac.go

Since database-clusters contain information about backup-storages and monitoring-instances, we need to check if the user has permission for those specified resources.

EVEREST-1477 | [RBAC] Enforce backup-storage and monitoring-instances permission for database-clusters

---

api/validation.go

EVEREST-1353 
Everest operator [lists objects in s3](https://github.com/percona/everest-operator/blob/e44c8cd8a71de9a1e52b94c8165a989b333f429f/controllers/databaseclusterbackup_controller.go#L780) to figure out the PG backup destination, but when adding a new backup storage, the Everest API doesn't check if there is a permission to list objects. 
**Related PRs:**
- https://github.com/percona/everest-operator/pull/523

EVEREST-1353 improve s3 validation

---

data/rbac/model.conf
pkg/rbac/rbac.go
pkg/rbac/validate_test.go
ui/apps/everest/public/static/model.conf

We added a custom globMatch function in https://github.com/percona/everest/pull/665 to satisfy the use case of being able to define  objects in the format`*/<resource-1>`, however, it broke the namespaces permission.
It looks like we do not really need a custom globMatch afterall, and our use-case can be handled well by the default `globMatch`. The reason for adding a custom function earlier was so that it could also satisfy a wildcard in the request (for example, in the `can` command), however, we never get a wildcard from the request side, except for the `can` command, so we can explicitly handle it there instead of adding any custom logic in the key matcher.
I'm also not really sure how the broken matcher got through, since it worked fine during the local testing, and also did not CI …

EVEREST-1469 | [RBAC] Fix broken matcher function

---

ui/apps/everest/.e2e/release/demand-backup.e2e.ts
ui/apps/everest/.e2e/release/init-deploy.e2e.ts
ui/apps/everest/.e2e/utils/monitoring-instance.ts

With this change we can select if we want to run a test for just single database or single size.
If we have a test which by default runs these combinations:
- psmdb - 1
- psmdb - 3
- pxc - 1
- pxc - 3
- pg - 1
- pg - 3
then by exporting SELECT_DB or SELECT_SIZE we can effectively filter for which db, size or both we want to run one or more tests.
This parameters will be added to the jenkins pipeline in case we want to do selective re-runs.

EVEREST-1467 - Add option to select database and size for UI E2E test

---

api/validation.go
api/validation_test.go

[EVEREST-1305](https://perconadev.atlassian.net/browse/EVEREST-1305)
Unless we are running a 1-node replset the minimum number of config servers is 3.
[EVEREST-1305]: https://perconadev.atlassian.net/browse/EVEREST-1305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

EVEREST-1305 fix minimun config server replicas for sharded clusters

---

api/database_cluster.go

EVEREST-1561
Nil dereference error appeared bc the code assumed that if there are any backups, at least one of them should be succeeded and have the creation date, which is not correct.

EVEREST-1561 fix nil dereference in PITR

---

commands/upgrade.go
pkg/upgrade/upgrade.go

Setting the `--dry-run` flag to the upgrade command will only run the pre-requisite checks, and not perform the actual upgrade.

EVEREST-1562 | Add --dry-run flag to upgrade cmd

---

api/database_cluster.go
pkg/rbac/rbac.go

Currently we allow the ListDatabaseClusters API call only if the user has access to all clusters. With this change, user will be able to always access this API, but the actual result itself is filtered on the basis of RBAC.

EVEREST-1534 | Filter the result of ListDatabaseClusters based on RBAC

---

.github/workflows/dev-be-ci.yaml
api/database_cluster.go
api/database_cluster_test.go

EVEREST-1583 
Since 1.16.0 `psmdb` operator introduced the `LatestRestorableTime` field. As it turned out, the field is not reliable (see [K8SPSMDB-1186](https://perconadev.atlassian.net/browse/K8SPSMDB-1186))
This PR removes the usage of the `LatestRestorableTime` field for mongo and puts back the heuristics logic (the latest restorable time = _now_ minus _the upload interval_)
the EVEREST-1584 ticket also describes some problems with the latest restorable time (taken from that new field), which would be probably fixed by this PR, but since I can't reproduce the issue at all I can't be sure it's fixed. 
[K8SPSMDB-1186]: https://perconadev.atlassian.net/browse/K8SPSMDB-1186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

EVEREST-1583 Mongo PITR: use heuristics again

---

ui/apps/everest/src/pages/databases/lastBackup/LastBackup.tsx
ui/apps/everest/src/pages/db-cluster-details/backups/backups-list/backups-list.tsx
ui/apps/everest/src/pages/db-cluster-details/db-cluster-details.messages.ts
ui/apps/everest/src/pages/db-cluster-details/restores/restores.messages.tsx
ui/apps/everest/src/pages/db-cluster-details/restores/restores.tsx

https://perconadev.atlassian.net/browse/EVEREST-1320
- add link from Last Backup error icon to backups page
- also display PITR message on backups tab

[UI] EVEREST-1320 Display PITR warning on backups page

---

ui/apps/everest/src/modals/restore-db-modal/restore-db-modal.tsx

`react-hook-form`'s `values` would override user backup type selection if the API values came after the user clicked the toggle, given we merged the API values with the default values.
The solution is to create an inner component and use `setValue` for this logic here, instead of `values`.
Thanks @tplavcic for noticing this bug with E2E tests.

Fix: wrong form values on restore modal

---

ui/apps/everest/.e2e/pr/db-cluster/db-cluster-overview.e2e.ts
ui/apps/everest/.e2e/pr/db-cluster/db-wizard/edit-db-cluster/resources-step.e2e.ts
ui/apps/everest/.e2e/utils/db-cluster.ts
ui/apps/everest/src/components/cluster-form/resources/constants.ts
ui/apps/everest/src/components/cluster-form/resources/resources.tsx
ui/apps/everest/src/components/db-actions/db-actions.tsx
ui/apps/everest/src/hooks/api/db-cluster/utils.ts
ui/apps/everest/src/pages/database-form/database-form.utils.ts
ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cards/resources-details.tsx
ui/apps/everest/src/shared-types/dbCluster.types.ts
ui/apps/everest/src/shared-types/dbEngines.types.ts
ui/apps/everest/src/utils/db.tsx
ui/packages/types/src/db-type/index.ts
ui/packages/utils/src/db/db.ts

https://perconadev.atlassian.net/browse/EVEREST-1399

EVEREST-1399 | bad resources toggle selection

---

api/database_cluster.go

EVEREST-1583
Everest was using the `CreatedAt` filed of the latest backup to calculate heuristics for the latest restorable time. Using `CompletedAt` makes more sense, because backups themselves take some time. 
--------
_Details:_
There is a failure case when a backup took some time (~3min) and the restore was made shortly after the first pitr option got available, so it caused the restore targeted the time _between_ `CreatedAt` and `CompletedAt` of the latest backup which caused the restore failed with 
```
snapshot's last write is later than the target time. Try to set an earlier snapshot. Or leave the snapshot empty so PBM will choose one.
```

EVEREST-1583 fix stuck restores

---

ui/apps/everest/.e2e/release/demand-backup.e2e.ts
ui/apps/everest/.e2e/release/init-deploy.e2e.ts
ui/apps/everest/.e2e/release/pitr.e2e.ts
ui/apps/everest/.e2e/release/scheduled-backup.e2e.ts
ui/apps/everest/.e2e/utils/db-cmd-line.ts
ui/apps/everest/.e2e/utils/table.ts

This adds a PITR test which:
- creates cluster
- adds data
- does full backup
- inserts more data for PITR and remembers current time
- waits for binlogs/oplogs to be uploaded to storage
- deletes data
- does PITR restore to time before data deletion
- checks data after restore

EVEREST-1558 Add PITR UI E2E test

---

ui/apps/everest/.e2e/playwright.config.ts

This needs to be removed because some assertions then wait for 12 minutes to fail which is too much.
As I can see we still have in each test group `test.describe.configure({ timeout: 720000 });` so we will try with this - if this is also going to lead to similar problems we will add something like `test.setTimeout(size * 120000);` with appropriate value into each test.

EVEREST-1635 - Remove custom global timeout in UI tests

---

.github/workflows/dev-fe-e2e.yaml
ui/apps/everest/.e2e/release/demand-backup.e2e.ts
ui/apps/everest/.e2e/release/init-deploy.e2e.ts
ui/apps/everest/.e2e/release/pitr.e2e.ts
ui/apps/everest/.e2e/release/scheduled-backup.e2e.ts

Needed for PG in scheduled-backup.e2e.ts (second schedule).
This change it to make the environment variables the same between `pr` and `release` tests so that there won't be any conflicts down the road.
PG cannot have two schedules on the same storage, so we need to add another storage in the same namespace since we want to have two schedules for the test.

Update EVEREST_BUCKETS_NAMESPACES_MAP in dev-fe-e2e.yaml

---

.github/workflows/dev-be-ci.yaml
.github/workflows/dev-build.yaml
.github/workflows/release.yml

EVEREST-107
At some point trivy started to fail the pipelines from time to time bc of the `TOOMANYREQUESTS` error. There are several workarounds but none of them 100% guarantee. 
Since we have Snyk which also scans for vulnerabilities, I don't think it's worth to go through all the "try and fail" path with workarounds, let's solve it ultimately - remove trivy scans from the Everest pipelines.

EVEREST-107 Remove trivy

---

api-tests/tests/database-cluster.spec.ts
api-tests/tests/database-engines.spec.ts

With the upgrade to PSMDBO v1.18.0 we need to update the engine versions.
There's also an issue with 1-node replset clusters that the operator team is looking into, until that is fixed let's use PXC instead of PSMDB for the monitoring tests.

EVEREST-1624 fix API tests

---

api/database_cluster.go
api/database_cluster_test.go

**Problem:**
EVEREST-1680
The password in the ConnectionURL was query-escaped twice. 
**Reason:**
The used `url.URL` uses the `encodeUserPassword` policy but not the `encodeQueryComponent` which means the characters like `,` are not escaped. However such characters can still appear in the DB passwords. So I saw the characters unescaped and thought the password wasn't escaped at all that's where an extra `url.QueryEscape` came from. 
**Solution:**
Do not use `url.URL` to build the connection URL

EVEREST-1680 ConnectionURL fix

---

ui/apps/everest/src/components/cluster-form/resources/resources.tsx
ui/packages/design/src/themes/everest/EverestTheme.tsx

[EVEREST-1684](https://perconadev.atlassian.net/browse/EVEREST-1684)
[EVEREST-1684]: https://perconadev.atlassian.net/browse/EVEREST-1684?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UI] EVEREST-1684 Remove blue background from resources step accordion

---

ui/apps/everest/src/pages/databases/DbClusterView.tsx
ui/apps/everest/src/pages/databases/emptyState/emptyState.tsx
ui/packages/design/src/themes/base/BaseTheme.tsx
ui/packages/ui-lib/src/icons/empty-state/empty-state.tsx
ui/packages/ui-lib/src/icons/index.ts

[EVEREST-1458](https://perconadev.atlassian.net/browse/EVEREST-1458)
- hide `Create Database` button from view if empty state is displayed
- keep `Create Database` button on empty filter results and non-empty db list results
- fix info icon style
- fix empty state icon style in dark mode 
[figma](https://www.figma.com/design/WasdpYdmJNoTn4zgFdHJcF/Everest-lib?node-id=1614-34489&node-type=instance&t=laU7OJ2gSgzgVaLI-0)
(this required using a complex css selector in order to override the colors and not use a different icon in dark theme) 
```
'&:not(:nth-child(n+8)), &:last-child': {           
```
^ this selects all the elements that are not blue 
[EVEREST-1458]: https://perconadev.atlassian.net/browse/EVEREST-1458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …

[UI] EVEREST-1458 Empty State Fixes

---

api/backup_storage.go
pkg/rbac/rbac.go

EVEREST-1699
The backup storage listing operation must be allowed if a given user has permissions to read at least one backup storage but the list should be filtered to include only the allowed backup storages.

EVEREST-1699 filter backup storages list based on RBAC permissions

---

api/database_cluster.go

EVEREST-1704
It was decided to not return the `ConnectionURL` for PXC from Everest API since there is no default format for such url.

EVEREST-1704 Remove pxc ConnectionURL

---

ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cards/card.types.ts
ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cards/db-details/connection-details.tsx
ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cards/db-details/db-details.tsx

[EVEREST-1704](https://perconadev.atlassian.net/browse/EVEREST-1704)
[EVEREST-1704]: https://perconadev.atlassian.net/browse/EVEREST-1704?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UI] EVEREST-1704 Hide PXC ConnectionURL

---

ui/apps/everest/src/hooks/rbac/rbac.ts

the useNamespace hook returns undefined data at a certain point, that leads to looping of checkPermissions function in ui/apps/everest/src/hooks/rbac/rbac.ts file because of default values = [] is anew every time

EVEREST-1712-fix-infinite-loop

---

pkg/cli/namespaces/remove.go

EVEREST-1740
The function that updates namespace may fail if other components have updated the namespace at the same time. 
This PR wraps the update function so it would retry if there is a conflict

EVEREST-1740 Wrap ns update

---

ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cards/pitr-details/edit-pitr.messages.tsx
ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cards/pitr-details/edit-pitr.tsx
ui/apps/everest/src/pages/login/Login.tsx

[EVEREST-1750](https://perconadev.atlassian.net/browse/EVEREST-1750)
Also added info text for first storage being used for mongo PITR.
[EVEREST-1750]: https://perconadev.atlassian.net/browse/EVEREST-1750?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UI] EVEREST-1750 Fix login focus, add info text for first storage in PITR modal

---

.github/workflows/dev-be-ci.yaml
cli-tests/Makefile
commands/install.go
commands/upgrade.go
go.mod
go.sum
pkg/cli/helm/flags.go
pkg/cli/helm/installer.go
pkg/cli/upgrade/steps.go

There’s an issue with Helm where during upgrades, if you provide values using `--set` (or equivalent flags), it will reset the values back to the defaults built into the chart.
To tweak this behaviour, helm offers the following 3 flags: reuse-values, reset-values and reset-then-reuse-values.
Each of these options changes the way values are applied during upgrades. Since we provide an option to change the Helm values from the CLI, we need to provide these flags as well.

EVEREST-1752 | add support for more helm upgrade CLI flags

---

.github/workflows/feature-build.yaml

EVEREST-1563
- rename `Custom build` to `Feature build` for consistency
- additional workflow input validation

EVEREST-1563 FB params validation

---

commands/namespaces/add.go
pkg/cli/namespaces/add.go
pkg/kubernetes/kubernetes.go
pkg/kubernetes/kubernetes_interface.go
pkg/kubernetes/mock_kubernetes_connector.go
pkg/output/command.go

Adds the following improvements to the namespaces command;
1. Setting `--take-ownership` for a namespace which is already managed by everest throws an error:
```sh
❯ ./bin/everestctl namespaces add everest --take-ownership
× invalid namespace (everest): namespace already exists and is managed by Everest. HINT: use 'everestctl namespaces update' to update the namespace
```
3. Trying to remove an operator shows a warning (note that the prevention of the removal is handled by the helm chart itself):
```sh
❯ ./bin/everestctl namespaces update everest                                                                                                               ││ …
```

EVEREST-1762, 1750 | Improvements to namespaces cmd

---

pkg/cli/namespaces/remove.go
pkg/kubernetes/database_cluster.go

* ignore `NotFound` error when trying to delete a DB cluster
* throw a warning when trying to remove a namespace that does not exist

EVEREST-1768, EVEREST-1766 | improvements for `namespaces remove` command

---

.github/workflows/feature-build.yaml

EVEREST-1563
The FB version wasn't displayed with the `v` prefix which is used for other builds (RC/Release/dev), this PR fixes it

EVEREST-1563 unify FB version

---

ui/apps/everest/.e2e/playwright.config.ts

EVEREST-107
With the old settings the `pr` `release` `upgrade` test suits were running slowly locally because they were launching Chrome instead of Chromium. So if Chrome is slow on your machine, you'll get the timeouts. 
This PR updates the settings so that all tests are running in Chromium by default

EVEREST-107 fix playwright config for slow chrome

---

go.mod
go.sum
pkg/cli/install/install.go
pkg/cli/namespaces/remove.go

* adds a check to ensure that the namespace specified in 'namespaces remove' command contains the 'app.kubernetes.io/managed-by=everest' label
* fixes some typos in post installation message

EVEREST-1789, EVEREST-1983 | [CLI] 'namespaces remove' command should remove Everest namespaces only

---

pkg/cli/helm/installer.go
pkg/cli/upgrade/steps.go
pkg/cli/upgrade/upgrade.go

In the Helm chart, we added a `helm.sh/resource-policy=keep` annotation to the Subscription to ensure that they cannot be removed during update operations. However, the new Subscription is not applied by helm since it already exists. This PR adds the `force=true` option so that the new Subscription annotations are applied.

EVEREST-1762 | Fix helm migration from 1.3 to 1.4

---

internal/server/handlers/rbac/database_cluster.go
internal/server/handlers/rbac/database_cluster_restore.go
internal/server/handlers/rbac/database_cluster_restore_test.go
pkg/rbac/rbac.go

* Fix some leftovers from [EVEREST-1707](https://perconadev.atlassian.net/browse/EVEREST-1707) - DBR permissions must use the cluster name
* `UpdateDatabaseClusterRestores` should have the same set permissions as `CreateDatabaseClusterRestores` 
[EVEREST-1707]: https://perconadev.atlassian.net/browse/EVEREST-1707?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

EVEREST-1709 | Update RBAC permissions & tests

---

pkg/cli/namespaces/add.go
pkg/cli/upgrade/steps.go
pkg/cli/utils/utils.go

EVEREST-1673 
**Problem:**
Everest Feature builds use custom helm chart, so we need to specify the directory when using helm with FBs. Upgrade to a FB was working fine for the previous Everest version (when legacy migration mechanism was applied), however for non-legacy db namespaces upgrade we were still missing the support for custom directory.
**Solution**
This PR:
- adds the custom dir support for non-legacy db namespaces upgrades
- introduces a small refactoring to avoid code duplication

Everest 1673 custom helm dir in db namespaces

---

.github/workflows/feature-build.yaml
dev/fb/cli.sh
dev/fb/helm.sh
dev/fb/vs.sh

By creating the VS deployment manifest during the build process and by embedding the helm chart and CLI binaries into the same FB artifact we can simplify the users experience of installing a feature build. Now, after downloading and unzipping 1 artifact, users only need to run `./helm.sh` or `./cli.sh` to install the FB.

EVEREST-107 Simplify Feature Builds

---

api-tests/tests/auth.spec.ts
internal/server/everest.go
internal/server/session.go
pkg/common/constants.go

EVEREST-1771
The `everest_token` cookie is a leftover from the old Everest. It is not used anymore and can be safely removed.

EVEREST-1771 remove unused cookie

---

.github/workflows/feature-build-pr.yaml
.github/workflows/feature-build.yaml
go.mod
go.sum

This PR adds the ability to automatically create feature builds for every PR labeled with `feature-build`. A new feature is built on every change to the PR.
To achieve this, the existing feature build workflow was changed to:
* Receive a catalog branch instead of an OLM bundle of an individual operator to upgrade
* Fallback to the default branches (main or production in the case of the VS repo) if the specified branch couldn't be found in the corresponding repo.
This new workflow assumes that the branches in the other repos have the same name of the branch of the PR.
E.g. if the branch of the PR is called `EVEREST-107-trigger-fb-automatically`, the branches for the everest-operator, everest-catalog, percona-helm-charts and percona-version-service must also be called …

EVEREST-107 Trigger FB automatically

---

ui/apps/everest/src/hooks/api/monitoring/useMonitoringInstancesList.ts
ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cards/db-details/db-details.tsx
ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cards/db-details/monitoring/monitoring.tsx
ui/apps/everest/src/pages/db-cluster-details/dbCluster.context.tsx
ui/apps/everest/src/pages/db-cluster-details/dbCluster.context.types.ts

- [EVEREST-1803](https://perconadev.atlassian.net/browse/EVEREST-1803)
- removed `canUpdateMonitoring` from `editable` condition, as overview monitoring card is related to the db permissions, not the monitoring instance  
- we need to check if db has access to **any** of the monitoring instances, instead of `*`, so I moved the logic to the top component, to not load db context with unnecessary computations 
[EVEREST-1803]: https://perconadev.atlassian.net/browse/EVEREST-1803?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UI] EVEREST-1803 Monitoring unavailable in db details widget when specific rule is set

---

ui/apps/everest/src/pages/common/empty-state/databases/index.tsx
ui/apps/everest/src/pages/common/empty-state/databases/messages.ts
ui/apps/everest/src/pages/databases/DbClusterView.tsx

[EVEREST-1781](https://perconadev.atlassian.net/browse/EVEREST-1781)
https://github.com/user-attachments/assets/96e258a5-2b8a-4d0e-aff4-2afef5adbe10
[EVEREST-1781]: https://perconadev.atlassian.net/browse/EVEREST-1781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UI] EVEREST-1781 Update message for empty state when user has no create permissions

---

.github/workflows/dev-fe-e2e.yaml

[![EVEREST-1855](https://badgen.net/badge/JIRA/EVEREST-1855/green)](https://jira.percona.com/browse/EVEREST-1855) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[EVEREST-1855]: https://perconadev.atlassian.net/browse/EVEREST-1855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

EVEREST-1855 Adjust FE e2e test to use APi server from current commit

---

ui/apps/everest/.e2e/release/init-deploy.e2e.ts

`init-deploy` test sporadically fails because suspending cluster can take a long time, so this increases the timeout.

Fix init-deploy test

---

go.mod
go.sum

[![EVEREST-1714](https://badgen.net/badge/JIRA/EVEREST-1714/green)](https://jira.percona.com/browse/EVEREST-1714) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
EVEREST-1714
**Problem:**
The DB can be in an ‘unknown’ state for a couple of seconds and we didn't want to show that to the user.
The related `everest-operator` PR adds the 'creating' state to the DB CR. From the BE side there is nothing left to do except of updating the `everest-operator` dependency to use the latest operator API, even though the DB statuses are not used in the codebase so far. 
**Related PRs:**
- …

EVEREST-1714 DB Creating status

---

ui/apps/everest/.e2e/pr/db-cluster/db-wizard/create-db-cluster/sharding.e2e.ts

[![EVEREST-1886](https://badgen.net/badge/JIRA/EVEREST-1886/green)](https://jira.percona.com/browse/EVEREST-1886) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Cluster deletion in the sharding test (pr/db-cluster/db-wizard/create-db-cluster/sharding.e2e.ts) takes about 24 minutes which makes the whole test run unnecessary long and sporadically failing.
The root cause is this: K8SPSMDB-1208: Cluster stuck in initialising due to failed scheduling cannot be deleted
Open
But it will be fixed in some future PSMDB operator release so this ticket is to provide a workaround until it is fixed. …

EVEREST-1886 - Fix cluster deletion in sharding test

---

.github/workflows/dev-fe-e2e.yaml

The github action node has 16G available so it should be safe to use 12G for minikube purpose.

Increase minikube memory to 12G for UI E2E tests

---

ui/apps/everest/.e2e/release/demand-backup.e2e.ts
ui/apps/everest/.e2e/release/init-deploy.e2e.ts
ui/apps/everest/.e2e/release/pitr.e2e.ts
ui/apps/everest/.e2e/release/psmdb-sharding.e2e.ts
ui/apps/everest/.e2e/release/scheduled-backup.e2e.ts
ui/apps/everest/.e2e/utils/generic.ts

At some point Playwright decided that they want to execute only afterAll hook (beforeAll hook is skipped) even if the whole test group is skipped so we need to add a condition in afterAll hook to not execute the content if the group is skipped.

Fix afterAll hook in release tests

---

ui/apps/everest/src/contexts/upgrade-everest/upgrade-everest.provider.tsx

With our current code, activating SSO (even without logging in with SSO) would cause the initial `GET /version` to be called for no valid reason.

fix: only called /version when logged in

---

ui/apps/everest/.e2e/release/init-deploy.e2e.ts
ui/apps/everest/.e2e/utils/db-wizard.ts

[![EVEREST-1904](https://badgen.net/badge/JIRA/EVEREST-1904/green)](https://jira.percona.com/browse/EVEREST-1904) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
We were passing custom DB options previously in our tests, but we were not checking if they were actually applied so this PR is to add assertion for that.
[EVEREST-1904]: https://perconadev.atlassian.net/browse/EVEREST-1904?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

EVEREST-1904 - Check if DB custom options passed correctly

---

ui/apps/everest/.e2e/setup/global.setup.ts

Currently if `minio` or `PMM` are not running the global setup just marks the setup as passed, but the tests will just fail and it doesn't make sense to run them.

UI tests - Fail global setup if storage or monitoring endpoints not created

---

internal/server/middlewares.go

[![EVEREST-1772](https://badgen.net/badge/JIRA/EVEREST-1772/green)](https://jira.percona.com/browse/EVEREST-1772) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Until we natively support HTTPS we should remove this directive.
[EVEREST-1772]: https://perconadev.atlassian.net/browse/EVEREST-1772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

EVEREST-1772 Disable upgrade-insecure-requests CSP directive

---

internal/server/handlers/validation/database_cluster.go
internal/server/handlers/validation/errors.go

[![EVEREST-1927](https://badgen.net/badge/JIRA/EVEREST-1927/green)](https://jira.percona.com/browse/EVEREST-1927) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
With this change, by default, we will be blocking updates to the storage size.
Note that we shall be changing this behaviour individually for each DB engine in their respective PRs/feature builds. This allows for controlled testing.
[EVEREST-1927]: https://perconadev.atlassian.net/browse/EVEREST-1927?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

EVEREST-1927 | Do not allow changing storage size

---

internal/server/handlers/validation/database_cluster.go
ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cards/resources/resources-edit-modal.tsx

[![EVEREST-1878](https://badgen.net/badge/JIRA/EVEREST-1878/green)](https://jira.percona.com/browse/EVEREST-1878) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Most of the code needed for supporting MongoDB storage scaling is already a part of this PR: https://github.com/percona/everest/pull/1191
So we need to only make minor tweaks to this
[EVEREST-1878]: https://perconadev.atlassian.net/browse/EVEREST-1878?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

EVEREST-1878 | MongoDB storage scaling support

---

ui/apps/everest/.e2e/utils/db-wizard.ts

[![EVEREST-1691](https://badgen.net/badge/JIRA/EVEREST-1691/green)](https://jira.percona.com/browse/EVEREST-1691) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
This should add more queries to the PMM QAN for PSMDB so the test should be more stable especially for 1 node setup.
[EVEREST-1691]: https://perconadev.atlassian.net/browse/EVEREST-1691?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

EVEREST-1691 - Make PMM QAN test more stable for PSMDB

---

.github/workflows/dev-be-ci.yaml
.github/workflows/dev-fe-gatekeeper.yaml
.github/workflows/feature-build.yaml

[![EVEREST-1883](https://badgen.net/badge/JIRA/EVEREST-1883/green)](https://jira.percona.com/browse/EVEREST-1883) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
**Update ubuntu images**
---
**Problem:**
EVEREST-1883
The Ubuntu 20.04 runner image will be fully unsupported by April 1, 2025 == no workflow execution if there is runs-on: ubuntu-20.04
Let's use `ubuntu-latest` and do not return to the problem anymore
**Related pull requests**
- https://github.com/percona/everest-operator/pull/706
- https://github.com/percona/everest-catalog/pull/57
[EVEREST-1883]: …

EVEREST-1883 update ubuntu images

---

.github/workflows/dev-be-ci.yaml
.github/workflows/dev-fe-gatekeeper.yaml

At some point Merge Gatekeeper sometimes started to fail ([example](https://github.com/percona/everest/actions/runs/14029878948/job/39275855694)) with 
```
Error: context deadline exceeded
```
There was the timeout of 5 min, let's increase it.

EVEREST-107 increase Merge Gatekeeper timeout

---

ui/apps/everest/src/components/time-selection/time-selection.test.tsx
ui/apps/everest/src/pages/database-form/database-form-body/steps/monitoring/monitoring.tsx

[![EVEREST-1962](https://badgen.net/badge/JIRA/EVEREST-1962/green)](https://jira.percona.com/browse/EVEREST-1962) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
The issue happened because of the new logic for the db form resolver: the schema validation happens before setting the monitoring value, and is not re-triggered properly.
https://github.com/user-attachments/assets/079d9131-6454-4d6c-a0fe-f2699a1315d3
[EVEREST-1962]: https://perconadev.atlassian.net/browse/EVEREST-1962?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UI] EVEREST-1962 Fix: trigger validaton after setting monitoring instance value

---

ui/apps/everest/.e2e/constants.ts
ui/apps/everest/.e2e/release/db-major-upgrade.e2e.ts
ui/apps/everest/.e2e/release/db-upgrade.e2e.ts
ui/apps/everest/.e2e/release/init-deploy.e2e.ts
ui/apps/everest/.e2e/release/pitr.e2e.ts
ui/apps/everest/.e2e/release/psmdb-sharding.e2e.ts
ui/apps/everest/.e2e/release/scheduled-backup.e2e.ts
ui/apps/everest/.e2e/utils/db-cluster.ts
ui/apps/everest/.e2e/utils/db-cmd-line.ts
ui/apps/everest/.e2e/utils/db-wizard.ts
ui/apps/everest/.e2e/utils/generic.ts
ui/apps/everest/.e2e/utils/version-service.ts
ui/apps/everest/src/components/time-selection/time-selection.test.tsx

[![EVEREST-1866](https://badgen.net/badge/JIRA/EVEREST-1866/green)](https://jira.percona.com/browse/EVEREST-1866) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
This PR adds a test for PSMDB database upgrade (major and minor) and it also covers MongoDB sharding.
The flow is following:
- start with lowest major version supported and latest minor version (eg. 6.0.19-16)
- do major upgrade to 7.0 non latest minor version (eg. 7.0.14-8)
- do minor upgrade to latest 7.0 version (eg. 7.0.15-9)
- do major upgrade to 8.0 (latest minor version since currently there is only one supported)
In the …

EVEREST-1866 - Add test for DB major/minor upgrade for PSMDB

---

go.mod
go.sum
internal/server/handlers/k8s/database_engine.go
internal/server/handlers/k8s/database_engine_test.go

[![EVEREST-1975](https://badgen.net/badge/JIRA/EVEREST-1975/green)](https://jira.percona.com/browse/EVEREST-1975) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Due to a bug in how we use the version library, PG DB versions are returned in an incorrect form. For example, `13.16` is parsed and returned as `13.16.0`, which is a non-existent version. This causes issues when trying to upgrade PG version during operator upgrades.
[EVEREST-1975]: https://perconadev.atlassian.net/browse/EVEREST-1975?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

EVEREST-1975 | [bugfix] DBengine min version preflight checks

---

internal/server/handlers/k8s/database_engine.go
internal/server/handlers/k8s/database_engine_test.go

[![EVEREST-1975](https://badgen.net/badge/JIRA/EVEREST-1975/green)](https://jira.percona.com/browse/EVEREST-1975) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
As a part of the operator upgrade preflight checks, Everest checks if the given DB engine version is greater than or equal to the smallest available DB engine version in the target release. However, this code assumes that all available versions shall be of the same major version -- which does not hold true for PG. This leads to incomplete preflight checks, i.e, users are allowed to upgrade the operator even if the DB is in a …

EVEREST-1975 | [bugfix] upgrade preflight checks for DB engine version

---

ui/apps/everest/.e2e/release/init-deploy.e2e.ts

[![EVEREST-1971](https://badgen.net/badge/JIRA/EVEREST-1971/green)](https://jira.percona.com/browse/EVEREST-1971) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
This adds 5 node clusters configuration for PSMDB/PXC and for PG it adds 2 node configuration into init-deploy.e2e.ts test.
[EVEREST-1971]: https://perconadev.atlassian.net/browse/EVEREST-1971?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

EVEREST-1971 - Add additional configurations into init-deploy test

---

.github/postgresql-client.yaml
ui/apps/everest/.e2e/release/db-upgrade.e2e.ts
ui/apps/everest/.e2e/release/demand-backup.e2e.ts
ui/apps/everest/.e2e/release/pitr.e2e.ts
ui/apps/everest/.e2e/release/psmdb-sharding.e2e.ts
ui/apps/everest/.e2e/release/scheduled-backup.e2e.ts

[![EVEREST-1981](https://badgen.net/badge/JIRA/EVEREST-1981/green)](https://jira.percona.com/browse/EVEREST-1981) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
We are having issue with PG client from version 16 with PG version 17 so it seems we need to use the newer client:
```
Error executing command: Error: Command failed: kubectl exec --namespace db-client postgresql-client-6f7b77ddd5-dlgng -- bash -c "PGPASSWORD='Uj+^j_1[K7*4o||d9SiCeW|J' psql -hpostgresql-3-dembkp-pgbouncer.everest-ui.svc -p5432 -Upostgres -dpostgres -t -q -c'\list'"
ERROR:  column d.daticulocale does not exist …
```

EVEREST-1981 - Fix PG client issue and Initializing status

---

ui/apps/everest/.e2e/release/psmdb-sharding.e2e.ts

Fix psmdb-sharding E2E test to not run if different database than PSMDB selected.

Fix psmdb-sharding.e2e.ts to not run when different DB selected

---

internal/server/everest.go
pkg/session/manager.go
pkg/session/manager_test.go

[![EVEREST-1106](https://badgen.net/badge/JIRA/EVEREST-1106/green)](https://jira.percona.com/browse/EVEREST-1106) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
EVEREST-1106
For the deleted built-in users, their access token was still valid until its natural expiration time.
To fix this, Everest server from now on checks if the user exists for every authenticated request for a built-in user. To avoid overloading k8s API with requests, Everest server uses a separate controller-runtime client with cache enabled for the needed resources.
[EVEREST-1106]: …

EVEREST-1106 Check built-in user existence on every request

---

.github/workflows/dev-be-ci.yaml
api-tests/tests/pxc-clusters.spec.ts

Looking at the recent integration test failures, we're getting 2 kinds of errors frequently:
Going through the events of the Everest server pods, it seems that the pod starts fine, things run okay for a while and then the pod crashes.
**Solution:** We will need a deeper …

EVEREST-107 | fix integration test failures

---

go.mod
go.sum

[![EVEREST-2026](https://badgen.net/badge/JIRA/EVEREST-2026/green)](https://jira.percona.com/browse/EVEREST-2026) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Reverts percona/everest#1306
Due to a bug in `v0.21.0`, we see only the first letter of the placeholder. This has not been fixed upstream yet, so we need to downgrade the version. 
See: https://github.com/charmbracelet/bubbles/issues/779
[EVEREST-2026]: https://perconadev.atlassian.net/browse/EVEREST-2026?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

EVEREST-2026 | Revert "chore(deps): bump github.com/charmbracelet/bubbles from 0.20.0 to 0.21.0"

---

ui/apps/everest/.e2e/release/init-deploy.e2e.ts

[![EVEREST-1981](https://badgen.net/badge/JIRA/EVEREST-1981/green)](https://jira.percona.com/browse/EVEREST-1981) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
The test currently fails for 1 and 5 node clusters since we only enable external access for 3 node clusters.
[EVEREST-1981]: https://perconadev.atlassian.net/browse/EVEREST-1981?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

EVEREST-1981 - Skip service type check if cluster size not equal to 3

---

pkg/common/constants.go
pkg/kubernetes/accounts.go
pkg/session/manager.go
pkg/session/manager_test.go

[![EVEREST-2029](https://badgen.net/badge/JIRA/EVEREST-2029/green)](https://jira.percona.com/browse/EVEREST-2029) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
**Problem:**
- EVEREST-2029: in https://github.com/percona/everest/pull/1339 Everest started to check the built-in users existence on every request to restrict the API access for tokens issued for already deleted built-in users. However it's not enough. Since the built-in users names do not have unique identifiers, if one deletes a user and creates another user with the same name, the token from the deleted user becomes valid …

EVEREST-2029,EVEREST-2021 Check password creation time

---

ui/apps/everest/.e2e/release/scheduled-backup.e2e.ts

PG scheduled backups don't have `cron-` prefix so this needs to work for all.

Fix scheduled-backup test

---

dev/README.md
dev/Tiltfile
dev/config.yaml.example

Add `enableFrontendBuild` to `dev/config.yaml` (`true` by default).
This is useful for FE devs, as we don't rely on Tilt's FE build to develop and, therefore, don't need double the resources rebuilding FE+BE when we do a change.

Optional Tilt FE build

---

ui/apps/everest/src/pages/databases/DbClusterView.tsx
ui/apps/everest/src/pages/databases/DbClusterView.utils.ts
ui/apps/everest/src/pages/databases/dbClusterView.messages.tsx
ui/apps/everest/src/pages/db-cluster-details/cluster-overview/db-errors/constants.ts
ui/apps/everest/src/pages/db-cluster-details/db-cluster-details.tsx
ui/apps/everest/src/pages/settings/namespaces/namespace-details/cluster-status-table.tsx
ui/apps/everest/src/shared-types/dbErrors.types.ts

[![EVEREST-2006](https://badgen.net/badge/JIRA/EVEREST-2006/green)](https://jira.percona.com/browse/EVEREST-2006) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
We want to be able to tell if the import failed based on `dbCluster.status.conditions`
1. error state and no .status.conditions then show the DB as Down :red_circle:
2. error state and a .status.conditions that indicates an import failure (exact error TBD) show a new state called Import Failed :red_circle: 
Example of cluster status with import failed: 
```
...
status: {
conditions: [{ type: "ImportFailed" }],
status: "error", …
```

[UI] Add ImportFailed status based on dbCluster.status.conditions

---

go.mod
go.sum
internal/server/handlers/k8s/kubernetes.go
internal/server/middlewares.go
pkg/oidc/oidc.go
pkg/session/blocklist.go
pkg/session/blocklist_test.go
pkg/session/manager_test.go

[![EVEREST-2210](https://badgen.net/badge/JIRA/EVEREST-2210/green)](https://jira.percona.com/browse/EVEREST-2210) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Is appears that original issuerUrl provided by user for OIDC configuration is not always the same as the one fetched from the OIDC provider's .well-known/openid-configuration (Microsoft Entra case). 
Need to add original issuer URL provided by user to Security-Policy headers as well, otherwise there will be issues with browser login using SSO.
[EVEREST-2210]: https://perconadev.atlassian.net/browse/EVEREST-2210?atlOrigin=eyJpIjo …

EVEREST-2210 Fix session blockList for MS Entra

---

api-tests/tests/monitoring-instances.spec.ts
go.mod
go.sum
pkg/pmm/apikey.go

CI used a debug build which provided a wrong PMM API key which lead to `"authorization failed, please provide the correct credentials"` failure in CI when using login-password
(Reported by the FE folks who also use PMM in CI)

EVEREST-107 fix PMM usage in CI

---

pkg/cli/uninstall/steps.go

[![EVEREST-1999](https://badgen.net/badge/JIRA/EVEREST-1999/green)](https://jira.percona.com/browse/EVEREST-1999) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[EVEREST-1999]: https://perconadev.atlassian.net/browse/EVEREST-1999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
EVEREST-1999 moved the CRDs to a separate helm chart, however, the CLI uninstall logic was not updated to clean up this Helm release.

EVEREST-1999 | update Everest CRDs uninstallation step

---

go.mod
go.sum
pkg/cli/upgrade/steps.go

[![EVEREST-2303](https://badgen.net/badge/JIRA/EVEREST-2303/green)](https://jira.percona.com/browse/EVEREST-2303) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Cannot perform upgrade using CLI:
```
:x: could not upgrade DB namespaces Helm charts: could not upgrade DB namespace 'everest-ui' Helm chart: template: everest-db-namespace/templates/hooks.yaml:1:94: executing "everest-db-namespace/templates/hooks.yaml" at <.Values.hooks.csvCleanup.image>: nil pointer evaluating interface {}.csvCleanup
:x:  Upgrading Helm chart
```
This issue was observed in `1.9.0-rc1`
We added some new types …

EVEREST-2303 | helm upgrade failure
