percona/everest

- api/backup_storage.go
- api/validation.go
- commands/install.go
- commands/upgrade.go
- data/crds/olm/everest-catalog.yaml
- data/crds/olm/olm.yaml
- install.sh
- pkg/install/install.go
- pkg/install/install_test.go
- pkg/kubernetes/backup_storage.go
- pkg/kubernetes/client/backup_storage.go
- pkg/kubernetes/client/client.go
- pkg/kubernetes/client/kubeclient_interface.go
- pkg/kubernetes/client/mock_kube_client_connector.go
- pkg/kubernetes/client/namespace.go
- pkg/kubernetes/kubernetes.go
- pkg/kubernetes/namespace.go
- pkg/kubernetes/olm_operator_test.go
- pkg/uninstall/uninstall.go
- pkg/upgrade/upgrade.go
Merge everything until
percona/percona-everest-cli@24c061392b983b3de4bb412cd2bd13961a5690d5
> EVEREST-665 merge latest CLI changes

- api-tests/tests/backup-storages.spec.ts
- api-tests/tests/database-cluster.spec.ts
- api-tests/tests/helpers.ts
- api-tests/tests/monitoring-instances.spec.ts
- api/backup_storage.go
- api/everest-server.gen.go
- api/monitoring_instance.go
- api/validation.go
- client/everest-client.gen.go
- docs/spec/openapi.yml
- go.mod
- go.sum
Merge everything until
percona/percona-everest-backend@69f606d2e8eb845d75085286a0a611fb5111e6be
> EVEREST-665 merge latest BE changes

- dev/Tiltfile
- dev/config.yaml
Merge everything until
recharte/everest-dev@d7a4f6ab1d3258a0bbc5491dc14fe575607359d9
> EVEREST-665 merge latest everest-dev changes

- .github/workflows/dev-build.yaml
EVEREST-655 
Build and push dev images on every commit to main
> EVEREST-655 DEV builds

- ui/apps/everest/src/pages/databases/DbClusterView.tsx
- ui/apps/everest/src/pages/db-cluster-details/backups/backups-list/backups-list.tsx
- ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cards/connection-details.tsx
- ui/apps/everest/src/pages/settings/monitoring-endpoints/monitoring-endpoints.tsx
- ui/apps/everest/src/pages/settings/namespaces/namespaces.tsx
- ui/apps/everest/src/pages/settings/storage-locations/storage-locations.tsx
- ui/packages/ui-lib/src/table/table.tsx
- ui/packages/ui-lib/src/table/table.types.ts
- ui/packages/ui-lib/src/table/usePersistentColumnVisibility.ts
- ui/packages/ui-lib/src/table/usePersistentColumnVisibility.utils.ts
Update until https://github.com/percona/percona-everest-frontend/commit/cd36ede4c0518780f23a0362ef763e608f6d9c13
> chore: update FE

- .github/workflows/dev-build.yaml
Since we switched to the monorepo, it's time to actually push the dev-latest images
> EVEREST-107 push dev-latest images

- install.sh
Merging PR from old CLI repo: https://github.com/percona/percona-everest-cli/pull/316
> EVEREST-885 fix install.sh for arm linux

- ui/apps/everest/src/pages/db-cluster-details/backups/backups-list/backups-list.tsx
- ui/apps/everest/src/pages/db-cluster-details/backups/backups.messages.ts
- ui/apps/everest/src/pages/db-cluster-details/backups/backups.tsx
https://jira.percona.com/browse/EVEREST-394
> [UI] Allow scheduling when backups are disabled

- .github/CODEOWNERS
- go.mod
- go.sum
FE devs will get notified about stuff in the /ui directory (FE devs exclusively, BE devs won't) and the BE devs will be notified about everything else.
> EVEREST-107 add codeowners

- ui/apps/everest/src/modals/restore-db-modal/restore-db-modal.messages.ts
- ui/apps/everest/src/modals/restore-db-modal/restore-db-modal.tsx
> [UI] EVEREST-898 Added alert warning for PG PITR

- .github/workflows/dev-be-ci.yaml
EVEREST-107
Remove the latest operator version check
> EVEREST-107 remove latest operator version check

- ui/apps/everest/src/pages/db-cluster-details/backups/on-demand-backup-modal/on-demand-backup-fields-wrapper.tsx
- ui/apps/everest/src/pages/db-cluster-details/backups/on-demand-backup-modal/on-demand-backup-modal.tsx
- ui/apps/everest/src/pages/db-cluster-details/db-cluster-details.messages.ts
[EVEREST-925](https://perconadev.atlassian.net/browse/EVEREST-925)
[EVEREST-925]: https://perconadev.atlassian.net/browse/EVEREST-925?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UI] EVEREST-925 Update 'Create backup now' dialog

- ui/apps/everest/.e2e/db-cluster-details/utils.ts
- ui/apps/everest/src/components/logical-physical-radio-group/LogicalPhysicalRadioGroup.tsx
- ui/apps/everest/src/components/schedule-form/schedule-form.messages.ts
- ui/apps/everest/src/components/schedule-form/schedule-form.tsx
- ui/apps/everest/src/pages/db-cluster-details/backups/scheduled-backup-modal/scheduled-backup-modal.messages.ts
- ui/apps/everest/src/pages/db-cluster-details/backups/scheduled-backup-modal/scheduled-backup-modal.tsx
[EVEREST-923](https://perconadev.atlassian.net/browse/EVEREST-923)
[EVEREST-923]: https://perconadev.atlassian.net/browse/EVEREST-923?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UI] EVEREST-923 Update 'create backup schedule' dialog

- ui/apps/everest/.e2e/auth.setup.ts
- ui/apps/everest/src/pages/databases/dbClusterView.messages.tsx
- ui/apps/everest/src/pages/db-cluster-details/backups/backups.messages.ts
- ui/apps/everest/src/pages/settings/monitoring-endpoints/monitoring-endpoints.messages.ts
[EVEREST-928](https://perconadev.atlassian.net/browse/EVEREST-928)
[EVEREST-928]: https://perconadev.atlassian.net/browse/EVEREST-928?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UI] EVEREST-928 Update all buttons to sentence case

- ui/apps/everest/src/pages/databases/lastBackup/LastBackup.tsx
[EVEREST-912](https://perconadev.atlassian.net/browse/EVEREST-912)
[related ticket for PITR errors](https://perconadev.atlassian.net/browse/EVEREST-905)
[EVEREST-912]: https://perconadev.atlassian.net/browse/EVEREST-912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UI] EVEREST-912 Add icon and tooltip to backups column

- ui/apps/everest/src/modals/restore-db-modal/restore-db-modal.messages.ts
- ui/apps/everest/src/modals/restore-db-modal/restore-db-modal.tsx
[EVEREST-938](https://perconadev.atlassian.net/browse/EVEREST-938)
[EVEREST-938]: https://perconadev.atlassian.net/browse/EVEREST-938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UI] EVEREST-938 Add storage name to PITR info alert when restoring

- api/validation.go
- api/validation_test.go
EVEREST-962 
created after https://percona.atlassian.net/servicedesk/customer/portal/2/HD-23050
> EVEREST-962 Bucket name validation

- ui/apps/everest/src/pages/databases/lastBackup/LastBackup.tsx
[EVEREST-967](https://perconadev.atlassian.net/browse/EVEREST-967)
[EVEREST-967]: https://perconadev.atlassian.net/browse/EVEREST-967?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UI] EVEREST-967 Last backup column should only show completed backups

- pkg/install/install.go
Fixes Everest operator version being incorrect.
> EVEREST-107: fix installed operator version

- .github/workflows/dev-fe-ci.yaml
EVEREST-950
Restores the logic that was temporarily removed from #191
> EVEREST-950: use make build-cli

- ui/apps/everest/src/hooks/api/db-cluster/useDbActions.ts
- ui/apps/everest/src/hooks/api/db-clusters/useDbClusters.ts
[EVEREST-1008](https://perconadev.atlassian.net/browse/EVEREST-1008)
[EVEREST-1008]: https://perconadev.atlassian.net/browse/EVEREST-1008?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UI] EVEREST-1008 Fix query key for dbActions

- ui/packages/ui-lib/src/db-toggle-card/db-toggle-card.stories.ts
- ui/packages/ui-lib/src/form/inputs/select/select.stories.tsx
- ui/packages/ui-lib/src/menu-button/menu-button.stories.ts
> [UI] Everest 995 select storybook

- ui/packages/ui-lib/src/form/inputs/auto-complete/auto-complete.stories.tsx
- ui/packages/ui-lib/src/form/inputs/select/select.stories.tsx
> Revert "Revert "Everest 996 add storybook to auto complete""

- ui/packages/ui-lib/src/db-toggle-card/db-toggle-card.stories.ts
- ui/packages/ui-lib/src/form/inputs/select/select.stories.tsx
- ui/packages/ui-lib/src/menu-button/menu-button.stories.ts
> Everest 995 select storybook

- ui/packages/ui-lib/src/form/inputs/text/text.stories.tsx
https://perconadev.atlassian.net/browse/EVEREST-992
added a story to the storyBook for the TextField component. The story is divided into two sub-stories: TextField and Textarea
> [UI]Everest 992-storybook-text-field

- ui/packages/ui-lib/src/form/inputs/radio-group/radio-group.stories.tsx
https://perconadev.atlassian.net/browse/EVEREST-997
Creating a story in Storybook for the RadioGroup component
> [UI]EVEREST-997-storybook-radio-group

- ui/apps/everest/src/pages/databases/DbClusterView.utils.ts
- ui/apps/everest/src/pages/databases/dbClusterView.messages.tsx
- ui/apps/everest/src/pages/databases/lastBackup/LastBackup.tsx
[EVEREST-1016](https://perconadev.atlassian.net/browse/EVEREST-1016)
[EVEREST-1016]: https://perconadev.atlassian.net/browse/EVEREST-1016?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UI] EVEREST-1016 Fix logic for "Inactive" status

- ui/apps/everest/.e2e/db-cluster-details/schedules.e2e.ts
- ui/apps/everest/src/pages/db-cluster-details/backups/backups-list/table-header/scheduled-backups-list.tsx
[EVEREST-1031](https://perconadev.atlassian.net/browse/EVEREST-1031)
[EVEREST-1031]: https://perconadev.atlassian.net/browse/EVEREST-1031?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UI] EVEREST-1031 Update retention copies display

- ui/packages/ui-lib/src/form/inputs/text-array/text-array.stories.tsx
https://perconadev.atlassian.net/browse/EVEREST-1040
> [UI] EVEREST-1040: text-array storybook

- ui/packages/ui-lib/src/icons/icons.stories.tsx
https://perconadev.atlassian.net/browse/EVEREST-1042
[Запись экрана от 2024-05-11 14-43-48.webm](https://github.com/percona/everest/assets/126169546/196a73b5-fd17-410e-a238-d14287c58ea9)
> [UI] EVEREST-1042: icons storybook

- ui/apps/everest/src/api/backups.ts
- ui/apps/everest/src/api/dbClusterApi.ts
- ui/apps/everest/src/hooks/api/backups/useBackups.ts
- ui/apps/everest/src/pages/db-cluster-details/backups/backups-list/backups-list.tsx
- ui/apps/everest/src/pages/db-cluster-details/backups/on-demand-backup-modal/on-demand-backup-modal.tsx
[EVEREST-1059](https://perconadev.atlassian.net/browse/EVEREST-1059)
[EVEREST-1059]: https://perconadev.atlassian.net/browse/EVEREST-1059?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UI] EVEREST-1059 Add cleanupBackupStorage to query param for delete db/backup

- ui/apps/everest/src/pages/db-cluster-details/backups/backups-list/backups-list.messages.ts
- ui/apps/everest/src/pages/db-cluster-details/backups/backups-list/table-header/backups-list-table-header.messages.ts
[EVEREST-819](https://perconadev.atlassian.net/browse/EVEREST-819)
[EVEREST-819]: https://perconadev.atlassian.net/browse/EVEREST-819?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UI] EVEREST-819 Fix warning for maximum PostgreSQL schedules

- ui/apps/everest/src/components/status-field/status-field.types.ts
- ui/apps/everest/src/components/status-field/status-field.utils.ts
- ui/apps/everest/src/pages/databases/DbClusterView.constants.ts
- ui/apps/everest/src/pages/databases/DbClusterView.utils.ts
- ui/apps/everest/src/pages/databases/dbClusterView.messages.tsx
- ui/apps/everest/src/shared-types/dbCluster.types.ts
[EVEREST-1056](https://perconadev.atlassian.net/browse/EVEREST-1056)
[EVEREST-1056]: https://perconadev.atlassian.net/browse/EVEREST-1056?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UI] EVEREST-1056 Add deleting state for db

- ui/apps/everest/src/consts.ts
- ui/apps/everest/src/pages/database-form/database-form-schema.ts
- ui/apps/everest/src/pages/settings/monitoring-endpoints/monitoring-endpoints.messages.ts
- ui/apps/everest/src/pages/settings/storage-locations/storage-locations.messages.ts
https://perconadev.atlassian.net/browse/EVEREST-1049
Changed "insert" to "enter" in all fields.
> [UI] EVEREST-1049: change insert to enter

- pkg/install/install.go
- pkg/install/install_test.go
> EVEREST-1080: make everest-olm a reserved namespace

- ui/apps/everest/src/pages/db-cluster-details/components/expanded-row/expanded-row.tsx
https://perconacorp.slack.com/archives/C0545J2BEJX/p1717417740055969?thread_ts=1717151221.509609&cid=C0545J2BEJX - issue
> EVEREST-1083-components-page-fix

- api/database_cluster.go
> EVEREST-1084: no backups or restores in components

- ui/apps/everest/src/components/welcome-dialog/welcome-dialog.tsx
[EVEREST-1009](https://perconadev.atlassian.net/browse/EVEREST-1009)
[EVEREST-1009]: https://perconadev.atlassian.net/browse/EVEREST-1009?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UI] EVEREST-1009 Open GitHub issues in new tab

- pkg/uninstall/uninstall.go
When running the uninstall wizard, it asks for confirmation for uninstalling. Selecting "n" proceeds to run uninstall anyway. This PR fixes this bug.
> EVEREST-1143 | [bug] Fix uninstall CLI wizard

- ui/apps/everest/src/pages/db-cluster-details/components/components.constants.ts
https://perconadev.atlassian.net/browse/EVEREST-1130
> fix: component "running" as success

- ui/apps/everest/.e2e/db-cluster/db-wizard/create-db-cluster/create-db-cluster.e2e.ts
- ui/apps/everest/.e2e/db-cluster/db-wizard/create-db-cluster/steps/basic-information-step.ts
- ui/apps/everest/.e2e/settings/upgrades.e2e.ts
- ui/apps/everest/src/pages/settings/namespaces/namespace-details/namespace-details.tsx
- ui/apps/everest/src/pages/settings/namespaces/namespace-details/types.ts
- ui/apps/everest/src/pages/settings/namespaces/namespace-details/upgrade-header.tsx
- ui/apps/everest/src/pages/settings/namespaces/namespace-details/upgrade-modal.tsx
https://perconadev.atlassian.net/browse/EVEREST-1124
> Everest 1124: show upgrade version

- ui/apps/everest/.e2e/db-cluster-details/schedules.e2e.ts
- ui/apps/everest/src/components/schedule-form-dialog/schedule-form-dialog.utils.ts
- ui/apps/everest/src/components/schedule-form-dialog/schedule-form/schedule-form-schema.ts
https://github.com/percona/everest/assets/90199600/f9ab3d2b-b854-498f-aab6-7caa2b48ac11
> Everest 1151 editing same schedule

- ui/apps/everest/.e2e/db-cluster/db-wizard/create-db-cluster/create-db-cluster.e2e.ts
- ui/apps/everest/.e2e/db-cluster/db-wizard/db-wizard-utils.ts
- ui/apps/everest/.e2e/db-cluster/db-wizard/edit-db-cluster/schedules.e2e.ts
- ui/apps/everest/src/hooks/api/backups/useScheduledBackups.ts
- ui/apps/everest/src/pages/db-cluster-details/backups/backups.tsx
https://perconadev.atlassian.net/browse/EVEREST-1154
> Everest 1154 edit schedules

- ui/apps/everest/.e2e/db-cluster/db-wizard/create-db-cluster/create-db-cluster.e2e.ts
- ui/apps/everest/.e2e/db-cluster/db-wizard/create-db-cluster/steps/backups-step.ts
- ui/apps/everest/.e2e/db-cluster/db-wizard/db-wizard-utils.ts
- ui/apps/everest/src/components/schedule-form-dialog/schedule-form-dialog.messages.ts
- ui/apps/everest/src/pages/database-form/database-form-body/steps/backups/backups.messages.ts
- ui/apps/everest/src/pages/database-form/database-form-body/steps/backups/schedules/schedules.messages.ts
- ui/apps/everest/src/pages/database-form/database-form-body/steps/backups/schedules/schedules.tsx
- ui/apps/everest/src/pages/db-cluster-details/db-cluster-details.messages.ts
https://perconadev.atlassian.net/browse/EVEREST-1146
> Everest-1146: update strings

- README.md
- ui/apps/everest/.e2e/global.setup.ts
- ui/apps/everest/src/components/welcome-dialog/welcome-dialog.messages.ts
- ui/apps/everest/src/components/welcome-dialog/welcome-dialog.tsx
https://perconadev.atlassian.net/browse/EVEREST-1089
> Change welcome message

- ui/apps/everest/.e2e/db-cluster-details/schedules.e2e.ts
- ui/apps/everest/src/hooks/api/backups/useScheduledBackups.ts
before:
https://github.com/percona/everest/assets/90199600/144fdd44-56fa-4733-9f6c-867c564bb2ac
after:
https://github.com/percona/everest/assets/90199600/21c6f88d-d1e7-4f63-8e7f-d280d03d380c
> EVEREST-1154-delete-request-cron

- ui/apps/everest/.e2e/db-cluster/db-cluster-overview.e2e.ts
- ui/apps/everest/.e2e/db-cluster/db-wizard/create-db-cluster/create-db-cluster.e2e.ts
- ui/apps/everest/src/pages/database-form/database-form-body/steps/resources/resources-step.messages.ts
- ui/apps/everest/src/pages/database-form/database-preview/database-preview.test.tsx
- ui/apps/everest/src/pages/database-form/database-preview/sections/resources-section.tsx
- ui/apps/everest/src/pages/databases/DbClusterView.tsx
- ui/apps/everest/src/pages/databases/dbClusterView.messages.tsx
- ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cluster-overview.messages.ts
- ui/apps/everest/src/pages/settings/monitoring-endpoints/monitoring-endpoints.messages.tsx
- ui/apps/everest/src/pages/settings/storage-locations/storage-locations.messages.tsx
[EVEREST-1175](https://perconadev.atlassian.net/browse/EVEREST-1175)
[EVEREST-1175]: https://perconadev.atlassian.net/browse/EVEREST-1175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UI] EVEREST-1175 Fix minor UI issues with texts

- pkg/install/install.go
- pkg/upgrade/upgrade.go
> EVEREST-1274: check k8s version during install/upgrade

- pkg/common/version.go
- pkg/install/install.go
- pkg/upgrade/upgrade.go
EVEREST-1274
Refactor from #544
> EVEREST-1274: refactor version check

- ui/apps/everest/src/consts.ts
- ui/apps/everest/src/pages/database-form/database-form-body/steps/advanced-configurations/advanced-configurations.messages.ts
- ui/apps/everest/src/pages/database-form/database-form.messages.ts
- ui/apps/everest/src/pages/settings/default-configurations/default-configurations.messages.ts
https://perconadev.atlassian.net/browse/EVEREST-1271
> [UI] EVEREST-1271 Enforce source range IP to have a network mask

- pkg/common/version.go
> EVEREST-1274: use git version for k8s version check

- pkg/common/version.go
> EVEREST-1274: fix version check

- ui/apps/everest/.e2e/db-cluster/db-wizard/create-db-cluster/steps/resources-step.ts
- ui/apps/everest/src/pages/database-form/database-form-body/steps/resources/resource-input/resource-input.tsx
- ui/apps/everest/src/pages/database-form/database-form-body/steps/resources/resources-step.utils.ts
- ui/apps/everest/src/pages/database-form/database-preview/database-preview.test.tsx
- ui/apps/everest/src/pages/database-form/database-preview/sections/resources-section.tsx
https://perconadev.atlassian.net/browse/EVEREST-1279
> EVEREST-1279 | use same decimal places on db preview as inputs

- ui/apps/everest/src/modals/restore-db-modal/restore-db-modal.tsx
- ui/apps/everest/src/pages/login/Login.tsx
[EVEREST-1232](https://perconadev.atlassian.net/browse/EVEREST-1232)
Fixes:
- inconsistent date format
- add enter key event for login
[EVEREST-1232]: https://perconadev.atlassian.net/browse/EVEREST-1232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UI] EVEREST-1232 Inconsistent date formats

- ui/apps/everest/.e2e/db-cluster/db-wizard/create-db-cluster/create-db-cluster.e2e.ts
- ui/apps/everest/.e2e/db-cluster/db-wizard/create-db-cluster/steps/resources-step.ts
- ui/apps/everest/.e2e/utils/db-cluster.ts
- ui/apps/everest/src/hooks/api/db-cluster/useCreateDbCluster.ts
- ui/apps/everest/src/hooks/api/db-cluster/useUpdateDbCluster.ts
- ui/apps/everest/src/pages/database-form/database-form-body/steps/resources/resources-step.tsx
- ui/apps/everest/src/pages/database-form/database-form-body/steps/resources/resources-step.utils.ts
- ui/apps/everest/src/pages/database-form/database-form-schema.ts
- ui/apps/everest/src/pages/database-form/database-form.constants.ts
- ui/apps/everest/src/pages/database-form/database-form.types.ts
- ui/apps/everest/src/pages/database-form/database-form.utils.ts
- ui/apps/everest/src/pages/database-form/database-preview/database-preview.test.tsx
- ui/apps/everest/src/pages/database-form/database-preview/sections/resources-section.tsx
- ui/apps/everest/src/utils/k8ResourceParser/index.ts
- ui/apps/everest/src/utils/k8ResourceParser/k8ResourceParser.test.ts
https://perconadev.atlassian.net/browse/EVEREST-1204
> Everest-1204: Gi units

- ui/apps/everest/src/pages/db-cluster-details/components/components.tsx
https://perconadev.atlassian.net/browse/EVEREST-1323
> Everest-1323 | Component page crash

- ui/apps/everest/src/pages/db-cluster-details/backups/backups-list/backups-list-menu-actions.tsx
> EVEREST-1408-restore-btn-rbac: fix of rbac permission for restore menu item

- ui/apps/everest/src/contexts/auth/auth.provider.tsx
before:
https://github.com/user-attachments/assets/d72955b8-553f-47a5-8b2f-7b3077f290f5
after:
https://github.com/user-attachments/assets/927b4292-b852-49f8-ac36-bf16db2d7a51
> [UI] EVEREST-1445-permissions-time-lag-after-login

- ui/apps/everest/.e2e/release/init-deploy.e2e.ts
- ui/apps/everest/.e2e/utils/db-wizard.ts
Over the last few weeks some changes have been introduced in the FE that broke the e2e release tests, this PR fixes them.
> EVEREST-107 fix release e2e tests

- ui/apps/everest/.e2e/db-cluster/db-cluster-overview.e2e.ts
- ui/apps/everest/src/components/status-field/status-field.tsx
- ui/apps/everest/src/pages/db-cluster-details/db-cluster-details.tsx
> [UI] EVEREST-1006-db-status-db-details: adding status

- ui/apps/everest/src/pages/database-form/database-form-body/steps/first/first-step.tsx
[EVEREST-1444](https://perconadev.atlassian.net/browse/EVEREST-1444)
```
...    
p, adminrole:role, database-engines, *, my-special-place/*
...
```
```    
...
p, adminrole:role, database-engines, *, my-special-place/*
p, adminrole:role, database-engines, *, the-dark-side/percona-postgresql-operator
...
```
[EVEREST-1444]: https://perconadev.atlassian.net/browse/EVEREST-1444?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UI] EVEREST-1444 Show only namespaces with at least one read permission for db engines

- ui/apps/everest/src/pages/db-cluster-details/backups/backups-list/backups-list-menu-actions.tsx
https://perconadev.atlassian.net/browse/EVEREST-1465
> Everest-1465 | Restore/new db permissions

- pkg/kubernetes/configmap.go
- pkg/kubernetes/kubernetes_interface.go
- pkg/kubernetes/mock_kubernetes_connector.go
- pkg/upgrade/upgrade.go
> Revert "EVEREST-1429 | Upgrading to 1.2.0 should bind all Everest accounts to the adminrole"

- ui/apps/everest/src/modals/restore-db-modal/restore-db-modal.tsx
[EVEREST-1398](https://perconadev.atlassian.net/browse/EVEREST-1398)
[EVEREST-1398]: https://perconadev.atlassian.net/browse/EVEREST-1398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UI] EVEREST-1398 Fix date format for restore modal

- ui/apps/everest/src/pages/db-cluster-details/components/components.tsx
https://perconadev.atlassian.net/browse/EVEREST-1390
> Everest-1390 | Fix bad isFetching

- api/validation.go
- api/validation_test.go
EVEREST-1303 
- do not allow to enable sharding when editing
- do not allow to enable sharding if psmdb version <1.17.0
> EVEREST-1303 Update sharding validation

- ui/apps/everest/src/pages/databases/expandedRow/ExpandedRow.tsx
- ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cards/resources-details.tsx
- ui/apps/everest/src/pages/db-cluster-details/components/components.tsx
- ui/apps/everest/src/utils/k8ResourceParser/index.ts
https://perconadev.atlassian.net/browse/EVEREST-1384
> Everest-1384 | total resources on cluster details

- api/database_cluster_backup.go
- api/validation.go
- api/validation_test.go
* on CreateDatabaseCluster
* on UpdateDatabaseCluster
* on CreateDatabaseClusterBackup
> EVEREST-1526 | Enforce backup storage permissions

- ui/apps/everest/src/pages/settings/namespaces/OperatorCell.tsx
- ui/apps/everest/src/pages/settings/namespaces/namespace-details/operator-versions-header.tsx
- ui/apps/everest/src/pages/settings/namespaces/namespaces.tsx
- ui/apps/everest/src/shared-types/namespaces.types.ts
https://perconadev.atlassian.net/browse/EVEREST-1524
> Everest-1524 |  Show "upgrade" if pending actions

- api/validation.go
- api/validation_test.go
[EVEREST-1544](https://perconadev.atlassian.net/browse/EVEREST-1544)
[EVEREST-1544]: https://perconadev.atlassian.net/browse/EVEREST-1544?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EVEREST-1544 fix minimum proxy replicas for PXC

- ui/apps/everest/src/components/cluster-form/resources/messages.ts
- ui/apps/everest/src/components/cluster-form/resources/messages.tsx
- ui/apps/everest/src/components/cluster-form/resources/resources.tsx
- ui/apps/everest/src/components/cluster-form/resources/resources.types.ts
[EVEREST-1541](https://perconadev.atlassian.net/browse/EVEREST-1541)
[EVEREST-1541]: https://perconadev.atlassian.net/browse/EVEREST-1541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UI] EVEREST-1541 Disable custom number of nodes for mysql databases

- ui/apps/everest/src/pages/database-form/database-form.utils.ts
[EVEREST-1545](https://perconadev.atlassian.net/browse/EVEREST-1545)
[EVEREST-1545]: https://perconadev.atlassian.net/browse/EVEREST-1545?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UI] EVEREST-1545 Fix default value of number of nodes for db edit

- ui/apps/everest/src/pages/settings/namespaces/OperatorCell.tsx
https://github.com/percona/everest/compare/EVEREST-1551-upgrade-pending-actions?expand=1
> EVEREST-1551 | only show upgrade when restart or upgrade needed

- ui/apps/everest/src/components/db-actions/db-actions.tsx
- ui/apps/everest/src/hooks/api/db-cluster/useCreateDbCluster.ts
- ui/apps/everest/src/pages/databases/expandedRow/ExpandedRow.tsx
- ui/apps/everest/src/pages/db-cluster-details/db-cluster-details.tsx
https://perconadev.atlassian.net/browse/EVEREST-1550
> Everest-1550 | empty db actions

- ui/apps/everest/src/components/db-actions/db-actions.tsx
[EVEREST-1556](https://perconadev.atlassian.net/browse/EVEREST-1556)
[EVEREST-1556]: https://perconadev.atlassian.net/browse/EVEREST-1556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UI] EVEREST-1556 Change Actions button to large size

- ui/apps/everest/src/components/cluster-form/resources/constants.ts
- ui/apps/everest/src/components/cluster-form/resources/messages.tsx
- ui/apps/everest/src/components/cluster-form/resources/resources.tsx
https://perconadev.atlassian.net/browse/EVEREST-1578
> [UI] EVEREST-1578 Fix validation for shards for mongodb with more than 1 node

- commands/install.go
- commands/uninstall.go
- commands/upgrade.go
- data/crds/olm/everest-catalog.yaml
- pkg/install/install.go
- pkg/kubernetes/catalog_source.go
- pkg/kubernetes/client/catalog_source.go
- pkg/kubernetes/client/gen.go
- pkg/kubernetes/client/kubeclient_interface.go
- pkg/kubernetes/client/mock_kube_client_connector.go
- pkg/kubernetes/environment.go
- pkg/kubernetes/gen.go
- pkg/kubernetes/kubernetes.go
- pkg/kubernetes/kubernetes_interface.go
- pkg/kubernetes/mock_kubernetes_connector.go
- pkg/uninstall/uninstall.go
- pkg/upgrade/upgrade.go
EVEREST-1590
OpenShift support
- Installation
- Upgrade
- Uninstallation
> EVEREST-1590: support for installation in OpenShift

- ui/apps/everest/src/pages/database-form/database-form-body/steps/backups/schedules/schedules.tsx
[EVEREST-1596](https://perconadev.atlassian.net/browse/EVEREST-1596)
[EVEREST-1596]: https://perconadev.atlassian.net/browse/EVEREST-1596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UI] EVEREST-1596 Create Backup Schedule option no longer visible in wizard if RBAC is enabled

- ui/apps/everest/src/components/status-field/status-field.types.ts
- ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cards/backups-details.tsx
- ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cards/card.types.ts
- ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cluster-overview.messages.ts
- ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cluster-overview.tsx
- ui/apps/everest/src/pages/db-cluster-details/cluster-overview/overview-section/overview-section.types.ts
[EVEREST-1066](https://perconadev.atlassian.net/browse/EVEREST-1066)
[EVEREST-1066]: https://perconadev.atlassian.net/browse/EVEREST-1066?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UI] EVEREST-1066 Add backups list to db overview card

- ui/apps/everest/src/components/db-actions/db-actions.tsx
https://perconadev.atlassian.net/browse/EVEREST-1352
> EVEREST-1352 | disable actions when deleting cluster

- ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cards/card.types.ts
- ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cards/db-details/connection-details.tsx
- ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cards/db-details/db-details.tsx
- ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cluster-overview.messages.ts
- ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cluster-overview.tsx
- ui/apps/everest/src/shared-types/dbCluster.types.ts
> [UI] EVEREST-1255 Add connection URL to details card

- ui/apps/everest/src/components/cluster-form/resources/constants.ts
- ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cards/db-details/connection-details.tsx
[EVEREST-1608](https://perconadev.atlassian.net/browse/EVEREST-1608)
- Also fixes wrong style for connection URL text field (padding and width on small screens)
Before:
After:
[EVEREST-1608]: https://perconadev.atlassian.net/browse/EVEREST-1608?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UI] EVEREST-1608 Fix custom proxy nr validation

- api/database_cluster.go
- api/validation.go
> EVEREST-1518: validate db engine read access during db cluster read/update/delete

- ui/apps/everest/src/pages/database-form/database-form.utils.ts
Fixes the flicker mentioned [here](https://perconadev.atlassian.net/browse/EVEREST-1187?focusedCommentId=417656)
Before: 
https://github.com/user-attachments/assets/4511b093-3b2a-470c-ab89-fb8a90467ce4
After: 
https://github.com/user-attachments/assets/5570fe78-7c17-4e85-a2bd-5e3037307b50
[EVEREST-1187]: https://perconadev.atlassian.net/browse/EVEREST-1187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UI] EVEREST-1187 Fix flicker for enable PITR switch in db edit mode

- ui/apps/everest/src/components/cluster-form/resources/resources.tsx
- ui/apps/everest/src/pages/database-form/database-form-body/steps/first/first-step.constants.ts
- ui/apps/everest/src/pages/database-form/database-form-body/steps/first/first-step.tsx
- ui/apps/everest/src/pages/database-form/database-form.constants.ts
- ui/packages/ui-lib/src/form/inputs/toggle-button-group/toggle-button-group.tsx
- ui/packages/ui-lib/src/form/inputs/toggle-button-group/toggle-button-group.types.ts
https://perconadev.atlassian.net/browse/EVEREST-1400
> EVEREST-1400 | correct default config servers

- pkg/uninstall/uninstall.go
> EVEREST-1254: fix extra output in log

- ui/apps/everest/.e2e/pr/db-cluster/db-wizard/create-db-cluster/create-db-cluster.e2e.ts
- ui/apps/everest/.e2e/pr/db-cluster/db-wizard/create-db-cluster/steps/basic-information-step.ts
- ui/apps/everest/src/pages/database-form/database-form-body/steps/first/first-step.tsx
https://perconadev.atlassian.net/browse/EVEREST-1642
> EVEREST-1642 | do now allow downgrade on restore

- ui/apps/everest/.e2e/playwright.config.ts
- ui/apps/everest/.e2e/release/demand-backup.e2e.ts
- ui/apps/everest/.e2e/release/init-deploy.e2e.ts
- ui/apps/everest/.e2e/release/pitr.e2e.ts
- ui/apps/everest/.e2e/release/scheduled-backup.e2e.ts
- ui/apps/everest/.e2e/utils/db-wizard.ts
- ui/apps/everest/.e2e/utils/table.ts
This fixes some timeouts so that the tests fail much sooner and also it fixes some of the flaky tests.
> EVEREST-1646 - Fix timeouts in UI E2E release tests

- ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cards/db-details/connection-details.tsx
[EVEREST-1680](https://perconadev.atlassian.net/browse/EVEREST-1680)
[EVEREST-1680]: https://perconadev.atlassian.net/browse/EVEREST-1680?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UI] EVEREST-1680 Fix overlapping label for connection url

- ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cards/backups-details.tsx
[EVEREST-1683](https://perconadev.atlassian.net/browse/EVEREST-1683)
[EVEREST-1683]: https://perconadev.atlassian.net/browse/EVEREST-1683?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UI] EVEREST-1683 Add sorting for backup table in details overview card

- .github/minio.conf.yaml
- .github/mysql-client.yaml
- .github/psmdb-client.yaml
- ui/apps/everest/.e2e/utils/db-cmd-line.ts
Part of fixes for running UI E2E tests on OpenShift, the other part was done in: https://github.com/percona/everest-qa/blob/main/scripts/percona-everest-ui.sh
> EVEREST-1591 - UI E2E OpenShift fix

- ui/apps/everest/.e2e/release/pitr.e2e.ts
- ui/apps/everest/src/consts.ts
- ui/apps/everest/src/modals/restore-db-modal/restore-db-modal.tsx
https://perconadev.atlassian.net/browse/EVEREST-1686
> EVEREST-1686 | change UI to 24h format

- dev/Tiltfile
* Everest API deployment is renamed to `everest-server`
> EVEREST-1620 | Fix Tiltfile

- ui/packages/ui-lib/src/form/inputs/text/text.tsx
[EVEREST-1688](https://perconadev.atlassian.net/browse/EVEREST-1688)
[EVEREST-1688]: https://perconadev.atlassian.net/browse/EVEREST-1688?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UI] EVEREST-1688 Blur text input on scroll

- cli-tests/tests/flow/namespaces.spec.ts
- commands/namespaces/add.go
- commands/namespaces/remove.go
- commands/namespaces/update.go
- pkg/cli/flags.go
- pkg/cli/install/install.go
- pkg/cli/namespaces/add.go
- pkg/cli/namespaces/remove.go
- pkg/cli/uninstall/uninstall.go
- pkg/cli/upgrade/upgrade.go
- pkg/cli/utils/utils.go
* Provide a hint message for `--take-ownership` flag
* Perform namespace ownership checks before the operator selection wizard
> EVEREST-1673 | [CLI] namespaces command improvements

- ui/apps/everest/.e2e/release/demand-backup.e2e.ts
- ui/apps/everest/.e2e/release/init-deploy.e2e.ts
- ui/apps/everest/.e2e/release/pitr.e2e.ts
- ui/apps/everest/.e2e/release/scheduled-backup.e2e.ts
- ui/apps/everest/.e2e/utils/db-wizard.ts
We have changed how the DB wizard is working so now we preselect database type before starting the wizard.
> Fix UI E2E for new create database button (preselect db)

- api/proxy.go
Hi! After creating the 25th cluster, I get an error message in browser Kubernetes Cluster is Unavailable and in operator log:
`{"level":"error","T":"2024-12-02T09:05:44Z","caller":"api/proxy.go:156","msg":"invalid character '\\x1f' looking for beginning of value\nfailed to transform response body"}`
Looks like same problem in https://github.com/percona/everest/issues/903
> EVEREST-1733 gzip support in proxy response modifier

- api/validation.go
- go.mod
- go.sum
> EVEREST-1261: change error message

- pkg/cli/namespaces/remove.go
- ui/apps/everest/src/components/code-copy-block/code-copy-block.tsx
- ui/apps/everest/src/pages/common/empty-state/namespaces/index.tsx
- ui/apps/everest/src/pages/common/empty-state/namespaces/messages.ts
- ui/packages/design/package.json
- ui/packages/design/src/themes/base/BaseTheme.tsx
- ui/pnpm-lock.yaml
https://perconadev.atlassian.net/browse/EVEREST-1737
> EVEREST-1737: add code commands to add namespaces

- ui/apps/everest/src/hooks/api/namespaces/useNamespaces.ts
- ui/apps/everest/src/pages/databases/create-db-button/create-db-button.tsx
- ui/apps/everest/src/pages/databases/dbClusterView.messages.tsx
https://perconadev.atlassian.net/browse/EVEREST-1304
https://github.com/user-attachments/assets/32ec475d-9166-435b-ad55-acc56f74156f
> [UI] EVEREST-1304 Fix create button size on click

- cli-tests/tests/flow/namespaces.spec.ts
- commands/install.go
- go.mod
- go.sum
- pkg/cli/flags.go
- pkg/cli/install/install.go
As described in https://perconadev.atlassian.net/browse/EVEREST-1769
> EVEREST-1769 | [CLI] unify behavior of provisioning DB namespaces between CLI and Helm

- cli-tests/tests/flow/all-operators.spec.ts
- cli-tests/tests/flow/mongodb-operator.spec.ts
- cli-tests/tests/flow/namespaces.spec.ts
- cli-tests/tests/flow/pg-operator.spec.ts
- cli-tests/tests/flow/pxc-operator.spec.ts
- go.mod
- go.sum
- pkg/cli/install/install.go
- pkg/common/constants.go
> EVEREST-1757 | [CLI] improve post-install message and make consistent with helm

- ui/apps/everest/.e2e/pr/db-restore/db-restore-to-new-cluster.e2e.ts
- ui/apps/everest/src/components/cluster-form/db-version/db-version.tsx
- ui/apps/everest/src/pages/database-form/database-form-body/steps/first/first-step.tsx
https://perconadev.atlassian.net/browse/EVEREST-1642
> Everest-1642 | fix restore db version

- ui/apps/everest/src/pages/common/empty-state/databases/index.tsx
- ui/apps/everest/src/pages/databases/DbClusterView.tsx
https://perconadev.atlassian.net/browse/EVEREST-1779
> EVEREST-1779 | do not show create db button without permissions

- ui/apps/everest/src/App.tsx
https://perconadev.atlassian.net/browse/EVEREST-1786
> EVEREST-1786 | disable OIDC userinfo endpoint

- ui/apps/everest/.e2e/playwright.config.ts
- ui/apps/everest/.e2e/pr/db-cluster-details/schedules.e2e.ts
- ui/apps/everest/src/hooks/api/db-cluster/useUpdateDbCluster.ts
https://perconadev.atlassian.net/browse/EVEREST-1725
> EVEREST-1725  | fix: switched tz conversion args

- README.md
I added the information for the HELM installation and updated the CLI installation section as well, but I would appreciate a second pair of eyes to review it, please.
> Add Helm Charts Guide for our Readme

- .github/workflows/feature-build.yaml
- dev/fb/vs.sh
Changes:
- `sh`  changed to `bash`  because [[ ]] is a bash-ism that isn't support by POSIX
-  changed the `sed` command parameters for non-Darwin machines
> EVERST-107 Update FB scripts

- commands/namespaces/update.go
Add hint how to make namespace managed by Everest
> EVEREST-1795 Extend error message for CLI `namespaces update` command.

- .github/workflows/auto-update-base.yaml
This workflow runs on every commit pushed to main and updates the base branch of every PR labeled with `auto-update-base`.
> EVEREST-107 Add workflow for auto-updating PR's base branch

- .github/workflows/feature-build.yaml
https://github.com/percona/everest/pull/1033 simplified the FB process, however we missed that we still need to add the FB version to the FB catalog image, this PR fixes it
> EVEREST-107 Fix FB catalog

- ui/apps/everest/src/pages/database-form/database-form.tsx
- ui/apps/everest/src/pages/databases/DbClusterView.tsx
[EVEREST-1800](https://perconadev.atlassian.net/browse/EVEREST-1800)
https://github.com/user-attachments/assets/97bd852a-926c-49df-ab8e-4e1e361acc10
[EVEREST-1800]: https://perconadev.atlassian.net/browse/EVEREST-1800?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UI] EVEREST-1800 Fix display of Add DB button, redirect from /new if state if empty

- go.mod
- go.sum
[![EVEREST-1837](https://badgen.net/badge/JIRA/EVEREST-1837/green)](https://jira.percona.com/browse/EVEREST-1837) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
> EVEREST-1837 update everest chart module

- ui/apps/everest/.e2e/pr/db-cluster-details/schedules.e2e.ts
- ui/apps/everest/src/components/time-selection/time-selection.constants.ts
[![EVEREST-970](https://badgen.net/badge/JIRA/EVEREST-970/green)](https://jira.percona.com/browse/EVEREST-970) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[EVEREST-970]: https://perconadev.atlassian.net/browse/EVEREST-970?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EVEREST-970 | change default schedule

- ui/apps/everest/src/hooks/api/namespaces/useNamespaces.ts
- ui/apps/everest/src/pages/common/empty-state/databases/messages.ts
- ui/apps/everest/src/pages/settings/monitoring-endpoints/monitoring-endpoints.tsx
[![EVEREST-1758](https://badgen.net/badge/JIRA/EVEREST-1758/green)](https://jira.percona.com/browse/EVEREST-1758) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
> EVEREST-1758 | add polling to namespaces page

- ui/apps/everest/src/pages/database-form/database-form-body/steps/first/first-step.test.tsx
On the first step of the wizard, make sure:
1. DB versions are sorted
2. The highest recommended version is pre-selected
3. When there's no recommended version, pre-select the highest
> test: recommended versions on wizard

- .github/workflows/cli-tests.yml
- .github/workflows/dev-be-ci.yaml
- .github/workflows/dev-fe-e2e.yaml
- .github/workflows/feature-build.yaml
- CONTRIBUTING.md
- Dockerfile
- commands/namespaces/list.go
- dev/everest-operator.Dockerfile
- dev/everest.Dockerfile
- go.mod
- packaging/everestctl_builder.sh
- pkg/cli/install/install.go
- pkg/cli/namespaces/add.go
- tools/go.mod
> EVERERST-107 update go version to 1.24

- ui/apps/everest/.e2e/release/psmdb-sharding.e2e.ts
- ui/apps/everest/.e2e/teardown/global.teardown.ts
[![EVEREST-1893](https://badgen.net/badge/JIRA/EVEREST-1893/green)](https://jira.percona.com/browse/EVEREST-1893) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[EVEREST-1893]: https://perconadev.atlassian.net/browse/EVEREST-1893?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EVEREST-1893 - Fix PSMDB sharding test and global teardown monitoring endpoints deletion

- go.mod
- go.sum
> EVEREST-107 | update helm chart dependency

- ui/apps/everest/.e2e/release/init-deploy.e2e.ts
[![EVEREST-1910](https://badgen.net/badge/JIRA/EVEREST-1910/green)](https://jira.percona.com/browse/EVEREST-1910) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[EVEREST-1910]: https://perconadev.atlassian.net/browse/EVEREST-1910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EVEREST-1910 - Add edit/scale cluster case to init-deploy test

- ui/apps/everest/src/components/cluster-form/resources/messages.tsx
- ui/apps/everest/src/components/cluster-form/resources/resources.tsx
- ui/apps/everest/src/pages/databases/DbClusterView.constants.ts
- ui/apps/everest/src/pages/databases/DbClusterView.utils.ts
- ui/apps/everest/src/pages/databases/dbClusterView.messages.tsx
- ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cards/resources-details.tsx
- ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cards/resources/resources-edit-modal.tsx
- ui/apps/everest/src/shared-types/dbCluster.types.ts
- ui/apps/everest/src/shared-types/kubernetes.types.ts
[![EVEREST-1876](https://badgen.net/badge/JIRA/EVEREST-1876/green)](https://jira.percona.com/browse/EVEREST-1876) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[EVEREST-1876]: https://perconadev.atlassian.net/browse/EVEREST-1876?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UI] EVEREST-1876 Storage scaling

- go.mod
- go.sum
> EVEREST-107 | update helm dev chart

- internal/server/handlers/validation/database_cluster.go
[![EVEREST-1875](https://badgen.net/badge/JIRA/EVEREST-1875/green)](https://jira.percona.com/browse/EVEREST-1875) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[EVEREST-1875]: https://perconadev.atlassian.net/browse/EVEREST-1875?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EVEREST-1875 | Allow storage expansion for MySQL

- internal/server/handlers/validation/database_cluster.go
- ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cards/resources/resources-edit-modal.tsx
[![EVEREST-1880](https://badgen.net/badge/JIRA/EVEREST-1880/green)](https://jira.percona.com/browse/EVEREST-1880) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Please see comment: https://github.com/percona/everest/pull/1228#pullrequestreview-2697315440
[EVEREST-1880]: https://perconadev.atlassian.net/browse/EVEREST-1880?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EVEREST-1880 | Allow storge expansion for PostgreSQL

- ui/apps/everest/src/components/cluster-form/resources/constants.ts
- ui/apps/everest/src/components/cluster-form/resources/messages.tsx
- ui/apps/everest/src/pages/database-form/database-form-schema.ts
- ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cards/resources/resources-edit-modal.tsx
note: modifications will be transferred to all 3 feature branches
https://github.com/percona/everest/pull/1230
https://github.com/percona/everest/pull/1227
https://github.com/percona/everest/pull/1191
> [UI] Block disk size descaling

- ui/apps/everest/.e2e/release/init-deploy.e2e.ts
[![EVEREST-1920](https://badgen.net/badge/JIRA/EVEREST-1920/green)](https://jira.percona.com/browse/EVEREST-1920) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[EVEREST-1920]: https://perconadev.atlassian.net/browse/EVEREST-1920?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EVEREST-1920 - Fix init-deploy.e2e.ts after fix for custom PG nodes

- ui/apps/everest/src/components/status-field/status-field.types.ts
- ui/apps/everest/src/components/status-field/status-field.utils.ts
- ui/apps/everest/src/pages/databases/DbClusterView.constants.ts
- ui/apps/everest/src/pages/databases/DbClusterView.utils.ts
- ui/apps/everest/src/pages/databases/dbClusterView.messages.tsx
- ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cards/db-details/basic-information/basic.tsx
- ui/apps/everest/src/shared-types/dbCluster.types.ts
[![EVEREST-1930](https://badgen.net/badge/JIRA/EVEREST-1930/green)](https://jira.percona.com/browse/EVEREST-1930) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
**Related pull requests**
- https://github.com/percona/everest-operator/pull/704
- https://github.com/percona/percona-helm-charts/pull/502
[EVEREST-1930]: https://perconadev.atlassian.net/browse/EVEREST-1930?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EVEREST-1930 Add upgrading state

- api/everest-server.gen.go
- client/everest-client.gen.go
- docs/spec/openapi.yml
- go.mod
- go.sum
[![EVEREST-1625](https://badgen.net/badge/JIRA/EVEREST-1625/green)](https://jira.percona.com/browse/EVEREST-1625) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
The DatabaseCluster openAPI schema is copied from the latest `everest-operator` bundle, there are a few fields & descriptions that were missing.
[EVEREST-1625]: https://perconadev.atlassian.net/browse/EVEREST-1625?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EVEREST-1625 align Everest API and everest-operator crd

- ui/apps/everest/src/components/cluster-form/resources/constants.ts
- ui/apps/everest/src/hooks/api/db-cluster/useDbActions.ts
- ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cards/resources-details.tsx
- ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cards/resources/resources-edit-modal.test.tsx
- ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cards/resources/resources-edit-modal.tsx
- ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cluster-overview.tsx
- ui/apps/everest/src/pages/db-cluster-details/cluster-overview/db-errors/constants.ts
- ui/apps/everest/src/pages/db-cluster-details/cluster-overview/db-errors/db-error-dialog.tsx
- ui/apps/everest/src/pages/db-cluster-details/cluster-overview/db-errors/db-errors.tsx
- ui/apps/everest/src/pages/db-cluster-details/cluster-overview/db-errors/messages.ts
- ui/apps/everest/src/shared-types/dbCluster.types.ts
- ui/apps/everest/src/shared-types/dbErrors.types.ts
[![EVEREST-1870](https://badgen.net/badge/JIRA/EVEREST-1870/green)](https://jira.percona.com/browse/EVEREST-1870) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[EVEREST-1870]: https://perconadev.atlassian.net/browse/EVEREST-1870?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UI: Limit disk size values to only integer values

- api/everest-server.gen.go
- client/everest-client.gen.go
- docs/spec/openapi.yml
- go.mod
- go.sum
- ui/apps/everest/src/components/db-actions/db-actions.tsx
- ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cards/backups-details.tsx
- ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cards/card.types.ts
- ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cards/db-details/advanced-configuration/advanced-configuration.tsx
- ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cards/db-details/basic-information/basic.tsx
- ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cards/db-details/monitoring/monitoring.tsx
- ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cards/resources-details.tsx
- ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cluster-overview.tsx
- ui/apps/everest/src/utils/db.tsx
[![EVEREST-1952](https://badgen.net/badge/JIRA/EVEREST-1952/green)](https://jira.percona.com/browse/EVEREST-1952) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[EVEREST-1952]: https://perconadev.atlassian.net/browse/EVEREST-1952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EVEREST-1952 | disable actions while upgrading or rescaling

- ui/apps/everest/src/pages/settings/namespaces/namespace-details/cluster-status-table.tsx
[![EVEREST-1975](https://badgen.net/badge/JIRA/EVEREST-1975/green)](https://jira.percona.com/browse/EVEREST-1975) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[EVEREST-1975]: https://perconadev.atlassian.net/browse/EVEREST-1975?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UI] EVEREST-1975 - Remove incorrectly added 0 patch version for upgrades

- ui/apps/everest/.e2e/release/db-upgrade.e2e.ts
[![EVEREST-1866](https://badgen.net/badge/JIRA/EVEREST-1866/green)](https://jira.percona.com/browse/EVEREST-1866) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[EVEREST-1866]: https://perconadev.atlassian.net/browse/EVEREST-1866?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EVEREST-1866 - Fix db upgrade test

- ui/apps/everest/src/hooks/api/db-cluster/useDbActions.ts
- ui/apps/everest/src/hooks/api/db-cluster/useDbCluster.ts
- ui/apps/everest/src/hooks/api/db-cluster/useUpdateDbCluster.ts
- ui/apps/everest/src/hooks/api/db-clusters/useDbClusters.ts
- ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cards/db-details/basic-information/basic.tsx
- ui/apps/everest/src/utils/db.tsx
[![EVEREST-1979](https://badgen.net/badge/JIRA/EVEREST-1979/green)](https://jira.percona.com/browse/EVEREST-1979) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[EVEREST-1979]: https://perconadev.atlassian.net/browse/EVEREST-1979?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EVEREST-1979 | fix bad query select override on upgrade modal

- pkg/kubernetes/operator.go
[![EVEREST-1899](https://badgen.net/badge/JIRA/EVEREST-1899/green)](https://jira.percona.com/browse/EVEREST-1899) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
> EVEREST-1899 | Add missing namespace arg in GetInstalledOperatorVersion

- pkg/cli/helm/installer.go
- pkg/cli/helm/utils/utils.go
- pkg/cli/helm/utils/values.go
- pkg/cli/helm/utils/values_test.go
- pkg/cli/install/install.go
[![EVEREST-2018](https://badgen.net/badge/JIRA/EVEREST-2018/green)](https://jira.percona.com/browse/EVEREST-2018) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[EVEREST-2018]: https://perconadev.atlassian.net/browse/EVEREST-2018?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EVEREST-2018 | fix port-forwarding instructions when TLS is enabled

- go.mod
- go.sum
> EVEREST-107 | Upgrade helm chart dependency

- ui/apps/everest/.e2e/release/db-upgrade.e2e.ts
- ui/apps/everest/.e2e/release/demand-backup.e2e.ts
- ui/apps/everest/.e2e/release/init-deploy.e2e.ts
- ui/apps/everest/.e2e/release/pitr.e2e.ts
- ui/apps/everest/.e2e/release/psmdb-sharding.e2e.ts
- ui/apps/everest/.e2e/release/restore-new-cluster.e2e.ts
- ui/apps/everest/.e2e/release/scheduled-backup.e2e.ts
- ui/apps/everest/.e2e/utils/db-cmd-line.ts
- ui/apps/everest/.e2e/utils/db-wizard.ts
[![EVEREST-1981](https://badgen.net/badge/JIRA/EVEREST-1981/green)](https://jira.percona.com/browse/EVEREST-1981) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[EVEREST-1981]: https://perconadev.atlassian.net/browse/EVEREST-1981?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EVEREST-1981 - Add test for specifying external DB access

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
[![EVEREST-1313](https://badgen.net/badge/JIRA/EVEREST-1313/green)](https://jira.percona.com/browse/EVEREST-1313) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[EVEREST-1313]: https://perconadev.atlassian.net/browse/EVEREST-1313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EVEREST-1313 | Add issue form templates

- go.mod
- go.sum
[![EVEREST-2078](https://badgen.net/badge/JIRA/EVEREST-2078/green)](https://jira.percona.com/browse/EVEREST-2078) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Helm chart PR: https://github.com/percona/percona-helm-charts/pull/546
[EVEREST-2078]: https://perconadev.atlassian.net/browse/EVEREST-2078?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EVEREST-2078 Update deps

- ui/apps/everest/.e2e/release/scheduled-backup.e2e.ts
- ui/apps/everest/.e2e/utils/table.ts
This fixes the issue where we didn't wait properly for backups to get deleted.
> Fix scheduled-backup test

- go.mod
- go.sum
> EVEREST-107 | update helm chat dependency 

- internal/server/handlers/rbac/kubernetes_test.go
- internal/server/handlers/rbac/load_balancer_config.go
- internal/server/handlers/rbac/load_balancer_config_test.go
- pkg/rbac/rbac.go
- pkg/rbac/testdata/policy-1-good.csv
[![EVEREST-2178](https://badgen.net/badge/JIRA/EVEREST-2178/green)](https://jira.percona.com/browse/EVEREST-2178) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
EVEREST-2178 
Add LoadBalancerConfigs RBAC & tests
[EVEREST-2178]: https://perconadev.atlassian.net/browse/EVEREST-2178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EVEREST-2178 LoadBalancerConfigs RBAC

- ui/apps/everest/src/components/cluster-form/advanced-configuration/advanced-configuration.tsx
- ui/apps/everest/src/components/cluster-form/advanced-configuration/messages.ts
[![EVEREST-2240](https://badgen.net/badge/JIRA/EVEREST-2240/green)](https://jira.percona.com/browse/EVEREST-2240) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[Screencast from 2025-08-27 15-43-55.webm](https://github.com/user-attachments/assets/4b299016-f0b2-4959-97e1-38bae5841965)
[EVEREST-2240]: https://perconadev.atlassian.net/browse/EVEREST-2240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Everest-2240 info icon tooltip for no load balancer config

- .github/workflows/feature-build.yaml
[![EVERST-107](https://badgen.net/badge/JIRA/EVERST-107/green)](https://jira.percona.com/browse/EVERST-107) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Remove catalog update from FB
> EVEREST-107 remove catalog update from FB

- ui/apps/everest/src/components/cluster-form/advanced-configuration/advanced-configuration.tsx
- ui/apps/everest/src/components/form-card/form-card.tsx
[![EVEREST-2244](https://badgen.net/badge/JIRA/EVEREST-2244/green)](https://jira.percona.com/browse/EVEREST-2244) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[EVEREST-2244]: https://perconadev.atlassian.net/browse/EVEREST-2244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EVEREST-2244 lbc field changes

- ui/apps/everest/src/components/cluster-form/advanced-configuration/messages.ts
[![EVEREST-2242](https://badgen.net/badge/JIRA/EVEREST-2242/green)](https://jira.percona.com/browse/EVEREST-2242) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[EVEREST-2242]: https://perconadev.atlassian.net/browse/EVEREST-2242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EVEREST-2242 change external access text

- ui/apps/everest/src/components/cluster-form/advanced-configuration/advanced-configuration.tsx
[![EVEREST-2254](https://badgen.net/badge/JIRA/EVEREST-2254/green)](https://jira.percona.com/browse/EVEREST-2254) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[EVEREST-2254]: https://perconadev.atlassian.net/browse/EVEREST-2254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EVEREST-2254, EVEREST-2256 Keep the selected value of LBC

- ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cards/db-details/advanced-configuration/advanced-configuration.tsx
- ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cluster-overview.tsx
[![EVEREST-2251](https://badgen.net/badge/JIRA/EVEREST-2251/green)](https://jira.percona.com/browse/EVEREST-2251) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://perconadev.atlassian.net/browse/EVEREST-2251
[EVEREST-2251]: https://perconadev.atlassian.net/browse/EVEREST-2251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UI] EVEREST-2251 - Show no config instead of disabled on overview card when load balancer config is empty

- ui/apps/everest/src/api/loadBalancer.ts
- ui/apps/everest/src/consts.ts
- ui/apps/everest/src/pages/settings/policies/load-balancer-configuration/configurations-list/configurations-list.tsx
- ui/apps/everest/src/pages/settings/policies/load-balancer-configuration/load-balancer-config-detials/load-balancer-config-detials.tsx
- ui/apps/everest/src/pages/settings/policies/load-balancer-configuration/load-balancer-config-detials/single-config-table/single-config-table.tsx
- ui/apps/everest/src/pages/settings/policies/shared/back-to/back-to.tsx
- ui/apps/everest/src/shared-types/loadbalancer.types.ts
- ui/packages/ui-lib/src/form/inputs/multiple-text-input/multiple-text-input.tsx
[![EVEREST-2252](https://badgen.net/badge/JIRA/EVEREST-2252/green)](https://jira.percona.com/browse/EVEREST-2252) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[EVEREST-2252]: https://perconadev.atlassian.net/browse/EVEREST-2252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Everest-2252: fix saving config bugs

- ui/apps/everest/src/components/cluster-form/advanced-configuration/advanced-configuration.tsx
[![EVEREST-2265](https://badgen.net/badge/JIRA/EVEREST-2265/green)](https://jira.percona.com/browse/EVEREST-2265) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[Screencast from 2025-09-01 15-02-07.webm](https://github.com/user-attachments/assets/0d9d2f73-e19e-41f1-8bbb-49c4566a46eb)
[EVEREST-2265]: https://perconadev.atlassian.net/browse/EVEREST-2265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EVEREST-2265 Default load balancer config select value

- ui/apps/everest/src/pages/settings/policies/load-balancer-configuration/load-balancer-config-detials/load-balancer-config-detials.tsx
[![EVEREST-2267](https://badgen.net/badge/JIRA/EVEREST-2267/green)](https://jira.percona.com/browse/EVEREST-2267) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[EVEREST-2267]: https://perconadev.atlassian.net/browse/EVEREST-2267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EVEREST-2267 Change back redirect functionality

- ui/apps/everest/src/components/cluster-form/advanced-configuration/advanced-configuration-schema.ts
- ui/apps/everest/src/components/cluster-form/advanced-configuration/advanced-configuration.tsx
- ui/apps/everest/src/pages/database-form/database-form-body/steps/advanced-configurations/advanced-configurations.test.tsx
- ui/packages/ui-lib/src/form/inputs/text-array/text-array.tsx
[![EVEREST-2270](https://badgen.net/badge/JIRA/EVEREST-2270/green)](https://jira.percona.com/browse/EVEREST-2270) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[Screencast from 2025-09-02 16-52-06.webm](https://github.com/user-attachments/assets/87e44dc6-873d-4441-8059-5278cf72e072)
[EVEREST-2270]: https://perconadev.atlassian.net/browse/EVEREST-2270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EVEREST-2270 Source range validation error and DB creating fixes

- ui/apps/everest/src/pages/settings/policies/load-balancer-configuration/load-balancer-config-detials/load-balancer-config-detials.tsx
- ui/apps/everest/src/pages/settings/policies/load-balancer-configuration/load-balancer-config-detials/single-config-table/single-config-table.tsx
- ui/packages/ui-lib/src/form/inputs/multiple-text-input/multiple-text-input.tsx
[![EVEREST-2269](https://badgen.net/badge/JIRA/EVEREST-2269/green)](https://jira.percona.com/browse/EVEREST-2269) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[EVEREST-2269]: https://perconadev.atlassian.net/browse/EVEREST-2269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Everest-2269: fix duplicate lg configs error

- ui/apps/everest/src/components/cluster-form/advanced-configuration/advanced-configuration.tsx
- ui/apps/everest/src/components/cluster-form/advanced-configuration/advanced-configuration.types.ts
- ui/apps/everest/src/components/cluster-form/advanced-configuration/advanced-configuration.utils.ts
- ui/apps/everest/src/pages/database-form/database-form-body/steps/advanced-configurations/advanced-configurations.tsx
- ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cards/db-details/advanced-configuration/edit-advanced-configuration/edit-advanced-configuration.tsx
[![EVEREST-2269](https://badgen.net/badge/JIRA/EVEREST-2269/green)](https://jira.percona.com/browse/EVEREST-2269) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[EVEREST-2256]: https://perconadev.atlassian.net/browse/EVEREST-2256?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EVEREST-2256]: https://perconadev.atlassian.net/browse/EVEREST-2256?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EVEREST-2269]: https://perconadev.atlassian.net/browse/EVEREST-2269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3M …
> EVEREST-2256: fix bad lb default load

- ui/apps/everest/src/components/cluster-form/advanced-configuration/advanced-configuration.tsx
- ui/apps/everest/src/components/cluster-form/advanced-configuration/advanced-configuration.utils.ts
- ui/apps/everest/src/pages/db-cluster-details/cluster-overview/cards/db-details/advanced-configuration/edit-advanced-configuration/edit-advanced-configuration.tsx
https://perconadev.atlassian.net/browse/EVEREST-2286
https://perconadev.atlassian.net/browse/EVEREST-2291
https://github.com/user-attachments/assets/23a59c3b-c9b0-4de3-836c-3969650426f6
> [UI] LBC fixes

- ui/apps/everest/.e2e/release/component-table-view.e2e.ts
- ui/apps/everest/.e2e/release/table-view.e2e.ts
- ui/apps/everest/.e2e/utils/table.ts
[![EVEREST-2241](https://badgen.net/badge/JIRA/EVEREST-2241/green)](https://jira.percona.com/browse/EVEREST-2241) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[EVEREST-2241]: https://perconadev.atlassian.net/browse/EVEREST-2241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EVEREST-2241 - Create a component table view test for a cluster
